package editDistance;

public class Main {

	public static void main(String[] args) {

		String DNA1 = "cctaattttttcgccacaagattagcaggaccgccagacgttcatcatcgcgtggcctcc\r\n" +
				"ttgttttgcatagtgtctagacagacagggaagtgttatgtgacgatccaggtgcaacat\r\n" +
				"ggcgcctacaggtcaacgcgacgagcacgacgctgacataattgtgtaccatgcacatac\r\n" +
				"tgcgatccgaaaggagccgaaaggtgttcggttcgtgctgatttgacctgaggagtgtca\r\n" +
				"gtgggccttccccacaatcgtcacgtggacgactaacagcataaggcatgtgccgcggtt\r\n" +
				"agtctgtacagtgctgggccgtaaaggctcgaggagccatgtggccgtgtcagacgacac\r\n" +
				"ttgagataacgtcaggctataacacgagtactccctcttcatgatcctttaccgtccaga\r\n" +
				"ccagtcgtctgtttacttttgtaccgacgctccggcgccgggtttgtgtagaaaaggcat\r\n" +
				"cgacaagggcgcaacacagctcgaccaatcgacgaatcgcgtcaggtaggtctaaacgat\r\n" +
				"gtaagattccccttataatcagatcgcagcggtccttagtggcccactgtctttcactga\r\n" +
				"ctgtcaaaactagtaaggtttacaaacacagagacatgttcccagaccatgtcggcacgt\r\n" +
				"cgttgcacagaccccggagctccagggtattgactgaattcgagcgaaacaccagcccgc\r\n" +
				"atcaagttgatagaatgcagaatccaagcttgcgcttataggatctgcgccgcattccta\r\n" +
				"ctttcgaggacatattagctcgcagtacgcacacaggtcagcaccgctacactatgtatc\r\n" +
				"ttagaaacgtcgagccagggaaatcaacattgcagtaaatgttccccgctgtccatccct\r\n" +
				"agcagcgcgctctctaaccgtctaccgccaagaggccttgcgtacgggtagccaggccag\r\n" +
				"acaagactttcgttggtatgctagtctcttctcgagcaccaattggtcggctgcctttgc\r\n" +
				"accccgtgtccatgctgctagcggccgggggccgaagaaacaaagacgtgaaggaagtct\r\n" +
				"gacacatctacgtcaccgaagccagtgtccgatacgcgggaaaagtgagcttcatgttaa\r\n" +
				"cgcggactctacgtgactggctgcacttatacagttacatggccgtctagcacgaccagg\r\n" +
				"tttaacgtcgcgaacaaaagatctagccacgacatttttaacgatggcgcgtgatcatta\r\n" +
				"accatacggcatcccaattaacgcgacatccaatctgagagtttaggcaaaactacgacg\r\n" +
				"gtaacgtttctagtccgacgtctggagcccagcgtagttctttcgacagatatatatccg\r\n" +
				"taaattacccagcttggacataccttccgaccagtcattcgcatgtctcgcagagctatg\r\n" +
				"cccacgcccaacttcaaagacgatacaatcaaaggttattacactaagtccaaatgcacg\r\n" +
				"gttgcactcagacaacatttgcggatcgtttgacaagacgacccttatgctatgtgcgtc\r\n" +
				"ttatctcttacatcctccacatgactgcgttagctccttttcccaacctaacctgtaaga\r\n" +
				"cttgcagaatatgtaagtagtctgatccggagcagccagacacgttttggatggactctt\r\n" +
				"ggagatgaattctcagataatattgagccctgccccctggcgaaggctactttctctcat\r\n" +
				"gtccccgtaaattaaaataaaccaccagaccgtacagtcaggaagcataatgtgatgttc\r\n" +
				"ttaactcctctgtcaatactatggatggtcggacttccatcccacagaagtggaagccta\r\n" +
				"gtacaggcgggagccctaccgaggtctacgtgaggactaccattgttaaaatacttcggc\r\n" +
				"taactggactgtctcttcgtgtagttactattctcgttccctttgccactgtgatgagtt\r\n" +
				"ccccatgccacccttcatgttaatcgctactggcaaggcagttggtgactaagctcgcag\r\n" +
				"catggaccggcttaactagagtggtgagcgatcctgccactctgatctccgatcagtcac\r\n" +
				"tcgttgacgacatgattgctagaatgtgtcttcgctacgtgcgcgtccagacgtatggac\r\n" +
				"gatgaaccggtctatgcttgtcggtggttggcgcccgtacgaaagcggcagtcctgttat\r\n" +
				"gaggacgatcaaggtccgcggtacaccagatgagtaaccaagagcacatgagtaagtaga\r\n" +
				"cggcgccagccttaacacgaccaaggctcggtcagtggtgttatttactgctgctatgga\r\n" +
				"tatgtgagtcattttttgcgtttcaggaccactggagatgtttggtatgtcaacagattc\r\n" +
				"tgttgtcttcagtaatcaatttcccgagaagtgaaatagcttgtggttaggcggcgtttc\r\n" +
				"gatcatattctccgtgccaacccggatccgttctccgactcgctggttctctatttcagg\r\n" +
				"agtaatccataattcgccgttggacgacacaggcgcagaccaactacggtcgaataatat\r\n" +
				"cctctattcatttgttttcgccgcccatacaagtttacccatcaaaaaagaacagtacat\r\n" +
				"gagagaccgggtgcgtcccgcgcaaacggtgtctcaggtggatgctcggtggcgtaagtt\r\n" +
				"tataaataagctagctacaccctgagaaaactggaactcttacgcgttagcacgctacag\r\n" +
				"gcatcttgtacagttacatcttagaggcccatactccgcaaaacacacataaagcgtgtt\r\n" +
				"gggagccttccgtaaactcgtccggcaaaatatacatcgataacgagttgctataggaat\r\n" +
				"agcgacgttaaatagctacctggccaattcacctcttttgtggttttttatcacggcctt\r\n" +
				"caatcctgctcatagtagtgtctataccacagtttagttaccatagattctggaggtgcg\r\n" +
				"gaagtttcgacgaacgagatgtagagcagcccgaactccgctatacgagttaaggaaatt\r\n" +
				"cgattgtggcgacattccgctgggataatgagagatagcctctactatgaatgcgggatc\r\n" +
				"gggcaatacccggtagcgtcactaacgaacgcaatctgttgaatctccctccggcacgcg\r\n" +
				"gagacagtcaaatcccgtgtttggcaatgcgaaaagcagccaatagaacggtcaaaaatt\r\n" +
				"tggcgtcgttctggaagtccatgcctaacagagtaggctttccggccactttggaaggtg\r\n" +
				"agagaagtcggacgatcggagcagcgatggcaatagtcgatcagaacgtactcccttcac\r\n" +
				"gcacccaccaatgtcaatatacgctcgacaagaattcatccccatttgttacagggcgaa\r\n" +
				"gcgcacctgcaacagagagatatcgtccgagattcaggaccatatccaaagtgtggtcgt\r\n" +
				"ccgcaagttcaagagttcgactgatgtttcagcgggccatttaatttttcgtgttgctct\r\n" +
				"tccatccccgagagcagggaggtaggtcccgacaaatacggtgtggcagattcgagcata\r\n" +
				"cataggtgcgcttcaaagtgacagcctggcgcatacaaacgatcgtccagtcacccaagc\r\n" +
				"ggtttgcagaaaggactacaaaagttctctcatatatccttcaaacaaccctacgcaggc\r\n" +
				"atactgggtttagccctgattagatccgaggtccacgaagctcggtttacacgtggcttg\r\n" +
				"gcaggaggaatcaaacaccgtcaggatctcataagccccgggattaaagtcaagtcggcc\r\n" +
				"cgctgattgcccggcttaagtgacctagcggaatcttcccacaagcggtatccgtttatg\r\n" +
				"gccgcattagaaacggtgatttttaaagggaactacaatagcctcgtcttgccacacctc\r\n" +
				"gggtgtcccataccataaactagtcaaccggcatggggcccatggttctccgtgtaaaat\r\n" +
				"taatgtaacgaaacgtgtggataaaggagactcttccctaaccctccagaacaaaaaagg\r\n" +
				"gggctgatataggtgctcatttctttcgtatagaagtgacgttaccccgctttggaactc\r\n" +
				"gataccgtcagactgaggcgggaaacttggggagctaccctcttcataaatgaactagtt\r\n" +
				"gttccataatcgtaaatggaggaattgttgtactggaagtatgtgcaatgaagcagtacc\r\n" +
				"gcttcaccgcaatttgcgtgcatgcaatgttactcggaagcatatatgtataacggtgtg\r\n" +
				"ccatttctctcgggccattttgctcgatccacgaggccccatagactctcacctgtgaag\r\n" +
				"gaaaacgagaacaattgttataacaacagacggacacacgtcgaactcaccaccgtttat\r\n" +
				"ctgagcaattttatgccatttatcccccagtcttcttccagttagtgttgtcagatctgg\r\n" +
				"agagtacgcgctaaagagtccctagtaagaggccactaaccgaagtcatagtcgcgctaa\r\n" +
				"ttggttaagcgctcaggagttccggctatttttgaagacatacatcgttcttcatacgct\r\n" +
				"gcgacagtgggtcgtgtcgaatattaccccgcggcagttcccctacgggcgcacgttagg\r\n" +
				"attaggcggaatatcaatgtcatagggtgatattatttcatgtatagcgggcatgtggac\r\n" +
				"aaactacttggggcttggctgctccagctaggtaaagccaacgggatcgaatgcgcgccc\r\n" +
				"gccctcagatgataagagtctgatcaggttcgatttgggcgggatttcacccactagtct\r\n" +
				"ggaactattaatagacggatttcatggctagggtcacctagaaaagagaccgccggctgt\r\n" +
				"ttctgctatggttaattactagacctgtgaagttgatccctactgctggccccgtacttt\r\n" +
				"acgataagagggtgtggttggcttgggccagcccctaggggacattacacttgcaattat\r\n" +
				"tagagcgctaaattgacgcccgacggggagattctgcttgttttcagctcatgctacgac\r\n" +
				"ccaactactggagtattccttaaataattaactttaggccgctgtagcaacacttagtga\r\n" +
				"aagcggctagttcacaagataagatgacccctcgtgcgccccaagttgacagtacgcgcg\r\n" +
				"ctgggacactttttgcctaaccaacagcgcgcaattaaggccgcgttcaaaggtaagttg\r\n" +
				"ccagtagcagggtcaaggtcgtacttgctgtcgcacactcttccgtggtttagtgcttaa\r\n" +
				"cacatgcaagttcgtagaaagatgaccttgcaaaatattaagtctccctgtatttgcggt\r\n" +
				"gggacctattcttaaaagtccacgaacttcaatctgttgagccacgccggactgggcccg\r\n" +
				"ggctttgggttatatcgccctgagagggagcgtggatatagacaagcccgaaataggatg\r\n" +
				"gctttctgagttgggcggcgtcttacacagtcgagaccggacgtaaggttccctcacccc\r\n" +
				"gggtagctgcggtcacgtgttggttcgcgttaagcggggggagagtgatgtctgttcggg\r\n" +
				"gtctccccgcgtacccccggaggaaaaacattacgacgatatacttaatacgttgataaa\r\n" +
				"tccctagatccgatacgctctcggtcctttagaggtcacaccttgtccgctttaagccgg\r\n" +
				"gccttccccgcgtgccatcgaagtataccctcctccaatcggaaacattctgttgatacc\r\n" +
				"tgcgcccataaaggactgcaaaatacatattcatcaaattcagccaaagccatttagtca\r\n" +
				"tggctgctcgagtgcaatttgtcaaccttcactgcgagcaagacccagtgcgcattcgca\r\n" +
				"ccctggctgcgctacgcccctaaatgctcggtcattcagtccgccaagcgattctcaact\r\n" +
				"gcagcaacataacaaccctatacttccgagcgctccgcaggtcacgacttcgagttactc\r\n" +
				"ttagcaaggtgtcggtaaccccggattaagggaatattcttgctccccacgtagtgtttc\r\n" +
				"cgggtttcctgataaagcgcccgccataggataattgaaatcattgaaaacatgtgtccc\r\n" +
				"gacgtgaccgccaaaaacgccctgacagaagtcagcttttcgtgcgaccggtctcagcca\r\n" +
				"cacagacggtatgacagctaaatcgtgacagaggagcgcgttcttccattgtgatgaatt\r\n" +
				"ccacggtacgggcccacagttattaaatctcgtactttggtaaagttgttgtaccgggtt\r\n" +
				"aacctaccttggcataactagatgtcggatttggcgcttaatcgccggtgcaagacggcc\r\n" +
				"ccagtagacaacgggttacagtaggggtttccctaaggtctgagtaaggacacccccgct\r\n" +
				"agtgcccaaaggattagcaacgatcaaaggaagacaggcgtgggcttctttgtcgcgacg\r\n" +
				"tccctactgcccactactagacggttaacgcacttcctccgcgttttagcacaagctgca\r\n" +
				"aggttatgggctctacaggcgaactgcggcggacgcggggcctgatatctatccctgtat\r\n" +
				"aagtgatgatagaaggggtaaacatagccgaagtgccggtcaagactcgcaggaagcgat\r\n" +
				"cgcaacagccttatgtacgtattatggtgtgtcaaagtctacgcacgctctcggctccgc\r\n" +
				"ccccgtacactttctacaccctgtccaggacggggaggcgcccattgccagttaactcac\r\n" +
				"agaagagttctccatgccaaattggcaatgcttcccacagagatctgatttcatcttagc\r\n" +
				"ctgagagtattgcagcatgtagacctggatcggttctagcagcgtcatgattttggtcag\r\n" +
				"gttttacgcaatccccggcaggggactaaaacggaaatagtctcccgtaccctaatcagc\r\n" +
				"cggcgggatattagagggaacgtgaagataatgtatcactcttggcgctaaaagctgaag\r\n" +
				"ttgtgcttggcacgagctggtcgaagacaagatgaaagcgcgtatcaggtacttttgtac\r\n" +
				"aattctcccacttacgtcattctctaggatcgctatatgctgtcagggcaccataccttt\r\n" +
				"gatcaagtttatatcccccagtcgaggttaattttacactacggttatgttgtggttgca\r\n" +
				"gcagcgagtatgctcttgctcacttctcgttgcacacctcgaatgatcttactgtgtcac\r\n" +
				"gaatacagaccgcccagcgagagatctcgtagttggcacctctaacaaattctatactgc\r\n" +
				"ccacgtttcgggaccttaaacgtaccgcatacagtttcctccgttgacatgttataatta\r\n" +
				"ctctatcgttacgagatttgtcgtataatgaataaagttggcgcccccgatccctacacg\r\n" +
				"ataatcacaaactatcgtgtctctcctcacgatggaaaccgtagtgcgatggactatcac\r\n" +
				"atgaactaataagggttggctgatagacacccgaaaccagacgcgccacacagcgggggg\r\n" +
				"tcggggtagtcgccatgcgagggccgttacacagtccctgggtgtaagatccaagggttt\r\n" +
				"caggtacgtttcgacgtaggcctatgaggactgcagggggccaatgtcctgcgtagcatc\r\n" +
				"ataaaaaaaggtccaaaaaggcccacatgtccagagaggtatgcctgaagtttcaacgta\r\n" +
				"gtggaggaatgctaggggagtgtgttctatcctgggcaaattactatttccctctattca\r\n" +
				"tacgtgaccttgataggaatggtgcatgaagactccgagccagatttctccgttagagag\r\n" +
				"gtactgttagactgctgtctgcgtctcccgtaagacatgatatttccgccatgctctcca\r\n" +
				"tcactgcctccctggctgttacataataggctcgaacacagaagggttttgcgggtccat\r\n" +
				"cggaatattttccatagtagacgccttcgttacgcctttatgagtagacatttagcactg\r\n" +
				"ctttagtccgtcgggtaagtcgacactctccgcaatgaacaacgttgtcgaggagtactc\r\n" +
				"gcctgccagaagagacgggatgaaaagagctctcgcatctaggtgggagatgcaggatct\r\n" +
				"gtttaacttggatttgccaccactgagcctccgcggacctaaggggttccgcaagcggtc\r\n" +
				"ttagtaaaactagtaggcccggctaacttccagggcacccgtctggtggccccctcattg\r\n" +
				"gaggtctcaagattgctgctgcctcagcgacctagttgactgttactttctgatcataag\r\n" +
				"cccttcccagaagtacaactagcacccacggaataaacgatggaatgcacatgaatccaa\r\n" +
				"gattgccgtaaaactctgccaacaaaatagattaccgataagcaggtccaagcgctaaag\r\n" +
				"ccttacgggggtttgcaacaaaattctcctgtaatttatcgtgatacgataccggcagca\r\n" +
				"taagtgatatccagctgcccaaactgcccaatcgtcgtaacagtatggacgggtatgctg\r\n" +
				"gttctgtttattccgttttacagtacatcgtcgttgtagaagtaccaccagtcgggatag\r\n" +
				"tagttaacggacatatgtacggttgtggcgcgcaacagccaacagaaattcccttcgtga\r\n" +
				"tactggggcacatgaactcctcaagcctgctaggataaactcgttcctcctgacgtcgta\r\n" +
				"tttcaacctcgaatccgtacatacgaactagatgctttgtgagtgggtcctctgagggtt\r\n" +
				"cgataaaacccccagtcttctcggacagtggacgccccgatgaggatgaatctaacgggg\r\n" +
				"aatccactatctaatgttattgaaccataccccatgtaaccagtatatcgttaaggtcat\r\n" +
				"catagctacttgtagcagtagataggcgcgtcaaggggtcatataggttgttatactaag\r\n" +
				"ctccaataacgtctagttgcgactaccacacgaacttgcccgccgttcagatgccccaac\r\n" +
				"gaatggtatttaatcgggcaagacacttgactcggaaaacgtataccatagttgaatacg\r\n" +
				"ggtactgcggacacagcatgcacggctatccacgtcaccttcaccatacgtagcctagct\r\n" +
				"aatgctaacatcctagagggctaagggagttatggtgggcaccggtacggtaactaacgt\r\n" +
				"cggccggcgaattccctcggtcttattgggatatattgagaagcgcgtcccaactcatta\r\n" +
				"ctgaagccatcgccattgcgcttatagtacctgatagagggatttggtggttcgtttcca\r\n" +
				"ggaagtccttttccacgctaggggcccctccgagttaagttctatgggggatcatatcat\r\n" +
				"aagattgaagagaagactgccagaagcgaattacgacgataatgttggaacagaagaagc\r\n" +
				"cgcattccttggttctttgtagcgcttgatgcccctcggttgcattgtttactgaaaacg\r\n" +
				"tcgaatatcgttaattgggtctgattaggaaagttaaaactccatttcaggagcctccgc\r\n" +
				"gtttagtccggtagtcagtctagcggataagaaggtgcgcaagacaataagccaataacc\r\n" +
				"aacatttgtgtagggcgactaagtcgtgacaacttggcatcatctggatagttataaacg\r\n" +
				"gtacggcgttgcaatcgatgcaaaagcagagacatagaccgttcgtaatcattaacagac\r\n" +
				"tggacaagggccgagacggtgaccacgaggacgccttgcagtactttcgattagcattcc\r\n" +
				"ctcccaagcgcacggcggtgcataaccaaccctatgtggatacgaacctttccatttaag\r\n" +
				"tgctaatcgcgggagtgggcaaggcaaatcatttcagggaccgattagtcgcacgcaaac\r\n" +
				"ggcatttgttatcgcttctactgtccgtatgacacgtgaagcgtcgtgttgtagccaatc\r\n" +
				"gcaatggtgcgtgccaatggcgtagaaatccgcgtgtactgatagaccattatgttcccg\r\n" +
				"cctataataggtactggcaatggttgtccaacctcgctatttcgcatccatcgagtatac\r\n" +
				"gtttcacatatattagcatttctgtagctacactgtgcactgagaacccagccgttgcct\r\n" +
				"agatatagcagagattcgtctgtcagaatccgggcaaggatattaatcccagttagctca\r\n" +
				"gaatattatgtagtaagccccattcaccacgcgccactttgcttggagccgaaagacgtt\r\n" +
				"acacatatctctatgcagcaaaatcaggcgtgctagtacgggatttcattcaccatccct\r\n" +
				"aacttatgaagtagtgatgtaaggcagcatacagaaagtaccagtgtcgtggtttgatac\r\n" +
				"gaacaccaccggaccgtaatggtgaagtaagctgcagggttgcaacgcggtaacgtggaa\r\n" +
				"agttctccactgcaagctacggaccactaagacaatacacgttatcctgaagtcactctg\r\n" +
				"atatcacgcggtgactacaagagaaatggcctgacatgtaactgtgactcggatcgggcc\r\n" +
				"tctatgaccacatctgaagctccatgtctggacaatcgttggacagttcatataccccaa\r\n" +
				"tgccctttagcaagataccagtgcgctggcgaaaccaatcgtatcgtcacgaggcggggc\r\n" +
				"ctattaagataatacagacgcattaatctaaacgagcgggaaacagtccgcggcctggac\r\n" +
				"agcccagccaacctgcttcgtcggtggtgtccagtgagtaccaatctgcacaggcgggct\r\n" +
				"cgaaggtttcaagccgagtatttatatgtgtacggtaccatcctattccttgtcgtcaac\r\n" +
				"tacactggtagcctaatttttaagagccccgcccccatagctaaagcttccggtggtgat\r\n" +
				"tatactacgtggcacactattaaggacatcggtaactgctaccttctgtgaaagatgcag\r\n" +
				"ctggtccgtctgtatcgacacccaaggcaggtcgatgctccaatcactaaccgatacggt\r\n" +
				"ggcacagcttaagcgcgaatacgtggagacattctgtaagtctgttctctaaagccatca\r\n" +
				"ctgtgacaggtaattcagaaggcaaggagtcgataaccacaccgagttcggctctgagac\r\n" +
				"gggtacggaagatattatggaactagatcctgaattttgcacgtgggctgccccacgaag\r\n" +
				"aaatcctcatgagtttcacggacatgggtaaatcagtgaaagttgccgggcgtttcatac\r\n" +
				"ggccagttggcctgtggaatggtcgatcgaaacccacattaggttgcccggacggaagca\r\n" +
				"tccaaaacttggagctcatcatttctctctccacgtgtcataaggtaaacgacccaaagc\r\n" +
				"ctactcagtacgcagaagacggtgagtaggggcatgctcattactggctgttctacacgt\r\n" +
				"ctagcaaggttttgcgagcaaggtctgggaggcggtccgggttacgctgactagaggttc\r\n" +
				"ggacaaaggatagtcatcccgctgaacgtgtatctagactcacgttccgtttttggacat\r\n" +
				"aatacttcggtagtttacaagacggcggtagagtggaatatatgtagcaagttagatgaa\r\n" +
				"ggctgacaatggcgatgatctccgaagtaccaagcggtgaccaaatcgagagccgtaatc\r\n" +
				"ggagagagcggagagttcccaccgtataggatgacaccgtctagtggtgccgatcgctta\r\n" +
				"ccgtctacactcgagtacctgtggggccgtctttcatcatccgacttgccactcggagac\r\n" +
				"gttgggcgagacgcacgttgagtgcgtctgtcgattttcgtattgattcgggaccaccgg\r\n" +
				"atctatcaagtgatagaggtgtagccagacgggggggggcagatgaaagacatcactgtt\r\n" +
				"gttcgcagccttactaaactgtcggacatagactctccgggtgcgaaccctcataggaac\r\n" +
				"ctgcaatacccgtacccccctgatggtccttggttaggttgagcgggggtactaatccat\r\n" +
				"atagtaacgggtatggaatagtctcgccgagaggcccgggcacctgagaataagcggaca\r\n" +
				"ataccggattaatactcatagcgtggataatgagtttaccggtttccactcttttgtaga\r\n" +
				"tcgaacagatgcgccgtttcgcagcctaatagcacgcaacgcgagtctgtgggccctaca\r\n" +
				"gggatggtgtgaatgtctcggtaaagctgaggtatccgaaatgggcagtaccattctgct\r\n" +
				"ctctctgcgatgcggctccataggataaatctacattttcctctctgattacgcggacag\r\n" +
				"gatttaatcgcaaataactagaacgaacgaacccgtgcttggtggtcgtatcatccatcc\r\n" +
				"gtgcgtactacacgtttcgaaagaggtgccccctgtggtatcttgtacgaattgttaccg\r\n" +
				"gccgtcccattcttgaaaattgacaatctcagacgttacacaaaataatcaaatacaacg\r\n" +
				"ggtcaactctgttataggaacagctagggggttaaggacgtaccggcaagtggaggggtc\r\n" +
				"gtgccatcggacagaaacctaatgtcgcgttctcgagactttatgtactactcctccgat\r\n" +
				"agggggcgacgtcttatgcagcctaggtaaaacgccgaacgtggattcgggtaacggtat\r\n" +
				"tggttgtgacaagaccccgctcggaactctgcttatccgtgcgtacgtgattgagtaaat\r\n" +
				"ccgatacatggtggactcgccctacccctcctcgcgtacgactcattgcgatcgttcatt\r\n" +
				"agactcccgccggtaattaggccggtagaaatgcgagataaatttgcggcgtagcgcgag\r\n" +
				"agtgcaccagccgactctggtccagttatgtgcctggtcaatctgagcgggtaattccca\r\n" +
				"gcgagggaaccgccttgttccagccaggtcgttgtggcaagtggctgaaggggtgcaccg\r\n" +
				"cgctaagtaaaagatccaaccgttaacggtttgcgttagaatttattatgagtagaccga\r\n" +
				"cacttactttcgtagccgacagtaagggatcgcaccagcggagtagactgacctgccgcg\r\n" +
				"gtaattaacacctatcgagatcctggttcttttcggtggcaggctaccacattgtagcgg\r\n" +
				"cgaaggtcgactaatcttgcgagaattactacggggtcagttcacaatccagttatgtaa\r\n" +
				"taaaccatgcgctattgggatgcatctacagttgctttagacctagtcagacagccttcg\r\n" +
				"ttgcggcgagcttcggtagcagtataatacatgttttatagtcccggagatccacgcttg\r\n" +
				"gatctccaacagttgcatccggcagcctcctgatgatgcttgcctggaaaggggtatcgt\r\n" +
				"tcattcacgcgttttaactaggcggtataaagtaactgctaaatggatcacgctgcgccg\r\n" +
				"cctcccctcaaatccgctatctaggagactccgactcaccaatgcattggaagatggcaa\r\n" +
				"aattctaggaagtgcatcggacctgcgccgctacgtaacaagtgtgcaggacatgaacat\r\n" +
				"taaccctcgtggttcatttgcgggttatgcagagcatgcttcatcgcaccatagccgctg\r\n" +
				"agatggactagccctaatgtgatctgaagtaggcaagatgctaacttataaacagtttca\r\n" +
				"gggttaatccttagaccaatgttaaatgaaagttggtaatctctcgtcgttgcgcggcgt\r\n" +
				"cctgatccgagacaccataagattatatgcttagactcgcagatcttgcaactgcctacc\r\n" +
				"atactttagtactctaggatcaggccgcaaatctgctatctattcacataatcgaattgc\r\n" +
				"gccagtgcgttgagcgcctcagactaatgtctgccgattcctcactcgggccttatccga\r\n" +
				"aatcacacgcgccttgatgtacgctacaatggattgtgcgtcttacccatattgtgacat\r\n" +
				"gtacattttggaagtggatccgaagtcgcccgacttttagcggtttggctacagaggacc\r\n" +
				"ctaacattctattcctcgtaagggggtccaggcatcatgaatcctcaagatggacccatc\r\n" +
				"gttcattataattatccggtgctataataatgtgcacgctccgatcgcagtcatttaaca\r\n" +
				"caaattttattatacgcaacactagaggagagaaagggcgcgcagagaactaatacagga\r\n" +
				"tcctccgttttgcgtacctgcatcgagttcctctgggagggttgtgtgctcgctatgccc\r\n" +
				"ccatacctgtcggaggattctgatctactgctaaatcaatttaagcagtttcatcaccag\r\n" +
				"atacgtggaccgtgcttagtgcgaggtggtgagtggcaaagagcaatggactcaccgtca\r\n" +
				"ctaatcttaccaatctgcgtctggcacagactagtaaaccactatcgctcgtcggagtgc\r\n" +
				"cacgacgacaccatagacaggtttcggttgttctagcttcctgtcaagaactctgctttt\r\n" +
				"acagtctaagccacggcgttctcagtaaagctgttgttccatgtataaaggccaactctc\r\n" +
				"attcgactgcgcgctcacattagacgcggggatgtcaagtcatggcaaactttgctttga\r\n" +
				"cgctccgacgagctaatgttcggtccagacaacctggagacgaactcgcttaacaggaac\r\n" +
				"ggagagtaagctacgcttcattccacatcgttccctccaaattggccgaaccatccccct\r\n" +
				"attgcttgtgagtagtgcctcgcattttttagcacggtacaaacagccactaagcgtagg\r\n" +
				"cggtaaggcttcgacttagcttcacgagctacgcacgaagcgtaaactcgcggctagtag\r\n" +
				"atcggacatttacacgtaccaaagcttttttcatcttgcaaaaaggacagattctcgaga\r\n" +
				"agaaaattatagcactaacatttcagacagttgaaaagacccagtttcgtctcacgagta\r\n" +
				"ctactttacaacgaagattgaggtgtatatggaaggtgggaagggtactgttcgctcctg\r\n" +
				"ctatacgacacacaacactcaccgggctggaatacttaacacgccgtggacacccgagcc\r\n" +
				"ctctcctgagactcaaagcagaggggtcgaagacggtagtctgtcccccgctccctagcg\r\n" +
				"tctgatctgaagcaggttaatggccaccccgccaccacagattaatccaagtcgctccat\r\n" +
				"taacactgtacctgctcccaccgtctaattcgatcgctccctagataagaccgtcttgtg\r\n" +
				"actaactaaatgtcagacttccgaataccgatggtatcgctttaagaaggagtgtcgtgc\r\n" +
				"ggcaattatggagaatatcgctttctgcttaattctggccggtataacaccgaccggatt\r\n" +
				"tggcggtacatttcctccagcccttaaataagtagaacaccggcaagaccacccagtttg\r\n" +
				"gtgagcagtagttcgcagcctctcgaatggacgtcagtagcgataattatcagcattggc\r\n" +
				"agaatgttaaggtatcgtccgtcgcgaaacatcgaattagttccgtaacggctccaatgt\r\n" +
				"tggctctagtgtgcctgcagggccagccatcgttatcgatgtagtactgtatataccaac\r\n" +
				"ccgaccatgagccttgaccacgattcagtcatggaggggtttccaccggattatggcctt\r\n" +
				"ctagtgaagcatgagattcgtggtctcagcaatgatccgaaacgatgtgtcctgggtatc\r\n" +
				"atataccgcgtcatgatctatgcggagtctgctacggtactaagccgtgaacactactat\r\n" +
				"catggaacgcaccgtacctactcgccgacgcatcgtccccgtgagtttaccctaatctac\r\n" +
				"accaaagcccatttccacgataaacattcattgtgtaataggagatcccacgcgcaggtt\r\n" +
				"tagaataaataaaaacattaacgttgactataagtatataacacggtactgctaatgagg\r\n" +
				"gtatgagccagcactgcgatatctactgagtggagagaaattcgatacaagcttacagtc\r\n" +
				"ataacactgcatgcagatagtggcctggtccgttgaagtgcctcaactagactgagatgg\r\n" +
				"ctgccctgcgaatagacaccgtgtttagggcacgatttcaaagacacccggctattcgtg\r\n" +
				"actaagctagccgggaagccgagccttgaactctgagcgacatactaccaatcagataca\r\n" +
				"aagtaaacgagttaactgcggatccttaggcttctacttcactcaacagaatagacatca\r\n" +
				"ttatcctgctgaaccatccataatgcatgcacgccctcacgcaaagaaatggtcgccggg\r\n" +
				"aaaaaacaactaactaacgggggctcacttatcctatagtagaaaggggagatcggatgc\r\n" +
				"ctggtaattgttgattacgtatttcacatgatagcgaagtattatttatcatagggcatg\r\n" +
				"cttaatgccgtgatgaaaaccagaaatgtgcatgtggacttaagacttagactgatgacg\r\n" +
				"ctttctggcattcagaccaatacttggacctttccgttctaacacgtggatgtgtgtacg\r\n" +
				"gccaactgccaaaaaggaactagtaaagatcaaacctcagctgactaatctgaacttgaa\r\n" +
				"aaacgagtcgtgacagacctgaatccaagcgtgttcgtcatactggctataaggaatttc\r\n" +
				"acagaaaatacgtataacgtctacgctggtgtgcctccgatgtgagttcgtcaagcatca\r\n" +
				"gtatggggctcctggacgagtgctcatgtgtgcttaattggttaatccgacggctaaaat\r\n" +
				"gagcaaggtcctgagctggggaaccgaatcaagtgacctaagccggtccgtggcttgcgt\r\n" +
				"tggtcctacaccgtggcctgatataaccgctttggtcgctcgacacagctaggggactgg\r\n" +
				"aaagggcgggagaggaccgcggttctccatcttaggcgagagggacttgactgcaaagct\r\n" +
				"ctgcgatggaggcaacatcgtcctcaactgacctttgtttatcacgctggccgcctttgc\r\n" +
				"gtctgacgtacacccccaataatggtcgacactgagtgagttaaacgttaatcattcgta\r\n" +
				"taatcgttgggcactctttgtgagcataaatgacgtacggcctaccgatgatgaaaattt\r\n" +
				"cacggcgcttagtgttagacttcaattacagccttacgctgcgcgcaggcggatgcagtc\r\n" +
				"ccaccaggggcagcccacaaagaccaagtagcgaaacttggcgttttttaagcgacgact\r\n" +
				"cgtactaaggaacaagcagggcatttcataagagatcgcaggaaccagctctattcatgt\r\n" +
				"atctcccccaagagtagcagggtatgaatgcgagatccctcttttatcccattacaatac\r\n" +
				"tcgccttttcggtgggtacaaagccttgtgagtttaacatttccgttttagccaccatat\r\n" +
				"agaatcatcacccgaataggaggacgaatggtaatactgtgttgttctagagcaatataa\r\n" +
				"tactcgaaagacgtccagaggtccagccgtggataataaacttgacgaaatggttccgtt\r\n" +
				"ttgtccggcaaagatagtgaactccaatatctggtattagggtcgttacaacccctatta\r\n" +
				"cctcttgctatagtacgaacgaacacgttgatttcttaaatacccgaagataggcaggtc\r\n" +
				"gggactgtcgctatagattcatgggtactcgtggacggggacgcgacggattgggcgtcg\r\n" +
				"tagagatactaattcggtaaagttcccgagttccggacatcgatctgagcttggtgatgt\r\n" +
				"agttctcgaaaggtccgtacggggcagcggcaagagagcgcaagctaatttatataagag\r\n" +
				"ttgttcaaacatacagtacgactgcttacacgtggtgaaaacatgggcaccgagatcggt\r\n" +
				"tccgcgcaacctatcaaatcgactacggtcagcgcttaaaccaccgacagcaacggagtt\r\n" +
				"gcttggcccagcagactggtcctgtatgggacgccaaggggcgctgtgtgcctttgtctc\r\n" +
				"acgaccacatgagcggtctgcataacgtcgatctcgcagtttatctatagacccttcgca\r\n" +
				"cggagccatacgattgtaacgtgcagttcctattatggctcaaatgtatgaagataacac\r\n" +
				"tattgggctctagtcgcgggattatccactctcgccaaacccgggtactttagcgtagac\r\n" +
				"tctctgggggcaaccacggaccactacgaatccggtacacattaagaaggagaatgctgg\r\n" +
				"cgtcaggctggactgcgaatagagtaggactaccgcatcagtaccaccggaacaatccgt\r\n" +
				"gttatacgtaacgactggtatttaaagaccgaacccacatccggtccaggtttcccgacc\r\n" +
				"tcccaaccatctttctaacgcgagttaagtacgaagcatggcaaggtagtaaggctggtg\r\n" +
				"ggcttgaaggaagactccccctcaagggagccttacgtgcaaagcagtgcggatcgatca\r\n" +
				"cgtcggagtcgtgcccttctcagctcgataggaggggagtcggcaggtgccatcccacgc\r\n" +
				"gtgcagcaaaaatgctctcgcaacagcgaaaaactgctaccccagacctgcttgaacaaa\r\n" +
				"atgcggtgatgctttcgaagctatcggctaatgtgactttcccgccagaaccggacagtc\r\n" +
				"tgcaacgttggccacctcccctaggctgcacttgaatcacagcggaagttacccggtatg\r\n" +
				"caacctactatggctagcttatccataacaacgtccagcatggtggcgtgagctgtcggt\r\n" +
				"agtcgcgtatcgagcccaggatgatcactaacacctctattaattctcgagctccagctt\r\n" +
				"cagtgcatgcagggacaaaatactaaaagtcctctcgacgaaacatccggctgccataga\r\n" +
				"ttacagcaccgtcaacaagcgccggaggtggaggacggtcctttaaggcctaaagcgaga\r\n" +
				"cggctacagccagcgaacagctctcgtgagcgaaggtcccgattaatagtagggtggata\r\n" +
				"gcgtgtcatggtgtagcacttgggcaagtcaactcattccgagtcttgtggcagtaaaag\r\n" +
				"gcaacatacagcctccgtaaggtcttcggagactttgcagtgttgcaactacggccctag\r\n" +
				"ctttgttactggtttaagcgggtagactcaagtgtacatcccggccgttctagagaagac\r\n" +
				"agcagtgctaacttttggtgtggtacttgtggttttaagggaaaatgtctagcgaaataa\r\n" +
				"attgctgctcacatccggtgcccaagcggccatgtctatacacagcaaagataaaataaa\r\n" +
				"ggtcaattgtaggacccgccaatattgcgacagacgtctttacccaccgactggtagcct\r\n" +
				"cactgacttgaagacgcaggaaggtgcacgatgtactgagtaaaagtatcgggaagacta\r\n" +
				"gtcaacagattgtgcgaatgaagggcaacccatcgggttatattgccgtggcgcaatacc\r\n" +
				"actgattacaaatctaaagggctaaacgttagaccgcgtcgccatctagctccatagggt\r\n" +
				"gttcatgttcacttccgatgcttgataccttattatcgcgcgatgctcgggtttggcaat\r\n" +
				"acggcgtaacctagcagccgatgtatgcccacctttccttccaatgagttgagtttcagc\r\n" +
				"ttggcaagcgaacgtaccggcagcggtgtgtaacagtcggcgagcgggcacaggctacgc\r\n" +
				"gattgatacacgtacgaacagagattccgcggtggcatagacaactgtcagccccaatta\r\n" +
				"tgaactatgcgcagcgatcccaggaggtgaaagaccaaaatcgcgcgcaaattcagaccc\r\n" +
				"cacatggctagctatatgtgctataggcgaggtacgccaccgaagggtatacactagttt\r\n" +
				"cacaaaatggacagtaaggaactgggatggccgtctcccattagtggagtttggatctaa\r\n" +
				"agttccaggacgtaataccgcaacaggggtttttaaggtggccgcttcgaatcagcttag\r\n" +
				"gtggctgcaagctcgaggtcaaaaaatagcaacagacatgcgtagaggacggaagatagc\r\n" +
				"acctgatgtcaatgcatttgccggctacattcggccgtccggagtcagcatcgaaagtct\r\n" +
				"ttacagtactaacgggactaactcgcattcccttgctagggtgtgccggatgtcctccga\r\n" +
				"ggcgattaaaagttcgttacggaacatctagtcgcccgtttaaaatcacttattctatcg\r\n" +
				"ttttcgggttgagcgcggactccattatagtcaatctgtggcaggttatccaacaataag\r\n" +
				"gccatcgtacctagtatcagagcgggtcggttgcgcgcacgtttttcggctctttggttg\r\n" +
				"tccaccccgtccttgactagccccgccggtcattcttccggtagactatccttcccgtac\r\n" +
				"tgctcgttcttctcaagttgcgcaaggaacgctcttggcgtgtcgtgaagttgcctgatg\r\n" +
				"tgcctttcgtttcagccaccataaattctcgtctatgtcaatactagacgccacctttga\r\n" +
				"gcagtctatgcgcactggttcttcaacaccgtgacatcgtcagactgtcactcggccctt\r\n" +
				"gccgacaattcaccatttagtgttggtttccacggataatactgcactgcgcaccgagcc\r\n" +
				"gttatgttaggacagatagtcttggccatactaacactaaaataaaggcttgtcgctgta\r\n" +
				"gacaatgatgcgcccagaagaatttggtggggaaggatagccgctggcccaatgagctgg\r\n" +
				"cttattcgccatgggttgtagacagacagtagtcagaactaatggtcccacatatcacgc\r\n" +
				"ttcgtttctgcggacagtatgttccccctcatgatactcagactcgagcctctattttag\r\n" +
				"caccaccttccccccggatattcaccaaccactaggactgtatctgcgcgagtttaagtc\r\n" +
				"ataggaaacaatgagttgctacggcgttgccaaactcccttaatcgctattgaatgccgc\r\n" +
				"cctaccacgacatcctacatcgggagattacgctatgcgcagtgttactgggctttgatt\r\n" +
				"gctaaaactgacggacctgcctcgtaccccctgcggataccctccttccagttctacaac\r\n" +
				"gatcgggttcatggtacaggcgccgtgagggaacgattatgtaaggcacaaattggtcat\r\n" +
				"gacttacgctcgccggtggtaacagcatccgaatgttgtgtcactctccggtaacacggt\r\n" +
				"gctaaataagtgacctaacttacacgtgggacctgagacttcattgatgttatgtgttgg\r\n" +
				"gtgagaagtcattatatcgtggatccgataatcccagcaaccacgccgaactcgctcaga\r\n" +
				"tatagaccagtccgtgtttccgtctcgaaccgaaaccaactgtttgtaaattgctcctct\r\n" +
				"cactaggccggatgatggcataacatagtgttcgccggtggacaggttggggcttttatt\r\n" +
				"cgccacagggaggacagtcatagttgtgtccttgttctctagacaaggaccaaagacgtt\r\n" +
				"cgcaccacatcgtcctgtgcgagaatagccttccgtcatgtaaacaggtgagattcagcc\r\n" +
				"caccgattcagcgcgcttccccagggcatgacagagtgcaagctgtaaacttacaggaga\r\n" +
				"tccaactggcgagtagtttcacgtgacgacgggggtattgtctgcgcatagttgcgtcac\r\n" +
				"gcaagttaaatatctatcgtgatgattcgaaacaactaagcacagatttcacgggctgct\r\n" +
				"gagatatacccagagcgatcatgagatgctgctgtattttgtgtgtcagtcggaatcgtt\r\n" +
				"atacaatagtcgggggtgaggtatataaaatagccgccgacggctatgacgcccgagtgt\r\n" +
				"gacagaggttcgcgctcgcattggttggatgcctgcgtaagcctaacgatagaccggacc\r\n" +
				"tgtcttatcctatcctattattcgcagcatacctagccttgagcactctcaacgtcggct\r\n" +
				"gtcgagtaatggcgtgacgataatcacatatcccattcgaggttgcctcaacgccaccgt\r\n" +
				"gcattcctgttgccacgggaaattggaggacagatccacgactgatgagatcactggatt\r\n" +
				"gactaccctgcagaccgaggtatccctctgggactatgtagctattcgtaagccctaacg\r\n" +
				"ctatactattgttaacagcgccttgcaatgctgtaaaccaatcttaatgaatttctcgtg\r\n" +
				"ccaatggttttgtcggttaggcggggactgacagagcaagttaggctttgctggtgcacg\r\n" +
				"ccgctagcagtcccggagctcatgtagatagggcgctaatcactaaggggttgtattact\r\n" +
				"cacgggacaagctggactggcccccccttggcgaaaaatccgatatacaaagaattactc\r\n" +
				"tcggtgttgacgactgtaattttgtcactactgagaacaagcgataagagcagaacgtcg\r\n" +
				"actaccttcatcctcgaatagataagacgccacactctccctgaatagcgatattctcca\r\n" +
				"gatagacacgaagaatgggatgcggacgacccattacgtactgccagctggaagttgcgc\r\n" +
				"cccccgtctcgtcttgccgtctgtcgcggtgagcctacggggcctgagcctctactttta\r\n" +
				"gaagcctggatttccccatgagctagttgagaacgtccgtagccgtctgggtgaaagcgc\r\n" +
				"cggctgttattggttccctcttcgcaaagttctggggattctaagatacgattctcctag\r\n" +
				"acattacaaaacgcgcccaaggtcttgcacgccgaacccaactgctcgagcacagtggat\r\n" +
				"tggcatataatagggcagtacgatccccttgtttattgaggtccccctccggtatatgag\r\n" +
				"tccataatggcctcagtactaattatcctcacttggattaccgtctcccttattcattct\r\n" +
				"cgtaacggctcagcagcatcggacgagatagatgccggatgagtcatgttagacatggat\r\n" +
				"cgatttgcgccataaactcttctgtcattgcacgtatgaaacactctccattaaatggtg\r\n" +
				"tgagcaagagataagcccaaatttaacatgcgaggattccggtacgaccaaaaggttgcc\r\n" +
				"cccctgtcctcaacaggctgtagtgctgtactcaaacaggcgcaccgagcctagggcagt\r\n" +
				"tgttgaggtccaaggtctggcaaccacccagtatattttaagtgcattcctttagaaatt\r\n" +
				"aaaggacatatcagaggggcggccagatttcaagactccgggaggcatataatacgcagt\r\n" +
				"ccaatgaggaccccaactcgttggcaatgcccggagagaagtatcaaggtccaaggaagc\r\n" +
				"cattcgaggtgagcatgctggatattgtgaaggctatctaactctgggaatcatcggata\r\n" +
				"aaaattcccaagacccatgcgtaaacaacccagcaactagctcttcggttgcacaaaaac\r\n" +
				"ggttataccctggggaattttatttttcgcggcgacccccttatttatgtgtctgcccat\r\n" +
				"ggcatgcgtatccggcttcaaaaaaacacttacttgaaccggacctaacacgaggatttc\r\n" +
				"cgtaaacccgcgcagatttgactgacccttaccgtgtcccgaatctcggtcccatccctt\r\n" +
				"agtccgttggctagcactcgaacttccttgttaaatctccgcctgagcggtcacgagatt\r\n" +
				"taaagggcgcagccgtgaagagctacaccttagcaatgtcggttgtctcgcagtaccagt\r\n" +
				"aggtatgctttactgcatagtctcccgaatggatctcggctaagtaaaaccactccttag\r\n" +
				"ggtaattaatacccaaagcggcccgattgccgatgtgttgtgctcactcacgctgtgtac\r\n" +
				"ctgtgcaccgggaacctgtgtgtagcagcatgcggcgagacttgactactgcgattttca\r\n" +
				"acaagttcagtctctggtgctctgccgcctggcacggcgtagcattgctgaagcgattat\r\n" +
				"tcgacctcgttttgggaaagcgtagcccgcatgatttagctgccctccaaggactcacta\r\n" +
				"tacaagtaagacgtggacctgcgtcgtctactggagagcaagatacaaggaagcatagat\r\n" +
				"cctctagtgagtaaggagctatctttacccgacacagctcaggtgcgtctaagcatcggc\r\n" +
				"tgcgtcggctccttgccgtgacttcccgcttgtcatctttatgttttcgtctaagatccg\r\n" +
				"acgcttggcctcttgatagtcatacaagcatcctgctgcatattatcttgaacagagtgt\r\n" +
				"cgtttttttatccggattacaaacgtggatccacccgaggaagcggtatgccaggtccta\r\n" +
				"acaggctggtggtatttacgccgatgcgggcttggcttacgataattataacgttggggt\r\n" +
				"taagaggctttctgagcttcatagccgggtgtgcataaggtaacgcgaggcatatgtaag\r\n" +
				"ttgggtaagtggactcaggccctcttacgcatgcgcaggcccatgtgacaagcgcgaacc\r\n" +
				"cgccaaactccagctcgtttacgccattgtccggcaatccgtcaacttactctcacaggc\r\n" +
				"cttctagttctcagggtcggttaagaatttaggcggtgtgggtagagacaatgcctgtaa\r\n" +
				"caccgtatcgaggcgaattcgtccacacttcggacggatcatatgactggcgccggatag\r\n" +
				"aaatagcgcatgcaacgacccaagactattatgcgctttcactccaacagtctgttcctt\r\n" +
				"gacacagtaaggtattacccacttattaataaatttatgacgagacggtcagtggataat\r\n" +
				"tgccagtgccaagctagacttatggcggctagctgggcgcgtccccgtcctcggctccgt\r\n" +
				"cactaacatggaagtttactactttgcgcgggctagagcgactctgaagatgaacttaat\r\n" +
				"tcatgagccgcgttcattgcatagctttcccacacaggcccatctccccaaggaccggat\r\n" +
				"aaaacaactcagtttgcgcaaaaattgccgccgaaatttttaaatgaggcgcccgcaccc\r\n" +
				"ttcaagacgcgccctggaactcctaaatagtgatatctctcaccacataagatcccaacc\r\n" +
				"atgagcggatgtatctttcgcatcgaccagctggtgctcagtacgcgccgaggagttgta\r\n" +
				"atacaggccgcctgtactatcaagcggaaggagaggatctccttcagaggaagacgcggc\r\n" +
				"atgctggtgaggagattgattgatgcacaaccgcttagaaggagacgtacataggagtaa\r\n" +
				"atctgcgctactgcgtttaatccttggacttggattcagcattctataattggcccagcg\r\n" +
				"atatttgcatctcaaggagagcacgatccagatatacggcagttgagtgagagcgaggga\r\n" +
				"tcgaaaatgaggtgcatcgttggcgttacaggatattggagattaacctcgtttgttctc\r\n" +
				"tttctaacaccaccacctgaggcgggctgctagatagtcaaatactccacccagagaacc\r\n" +
				"acacacgacgcccgacgttcatgtagcccactcaccacgccgggggaacccaatctcagt\r\n" +
				"aagtcgaggcggatcaggtatttctatcatcttttaacgtagcggatgaaaaacaaacag\r\n" +
				"ggacggcttcacgggtgagggaagtcagtctcgatcatcaacgcggtataggggccgtgg\r\n" +
				"ggctgccgagctattaagaaaatagcgcactacagccgtctcgagtagtatcgtacatcg\r\n" +
				"cccttgttgtgtcgttgagtgcttcgcgttccaggtcccagccatgctctcacgtgtaaa\r\n" +
				"cttatgatggtgtgggaccgttctcgccgtgcaacagatctttccacgattttagcgggt\r\n" +
				"attggattcccccctaaactacgaatcaatccaaaaaatctacggaacctagtgatgttt\r\n" +
				"gtgtagttccagcattcgaggcgttcactagccgctggggacgggccgcgcgctctttgg\r\n" +
				"gccatccgaagtgctacgaatgtgagcacactccatttcctctcgcgctacgttttcaaa\r\n" +
				"tgctcccggatcaataggtttgcacgggctagtacgcacgcacataaggacagctgggat\r\n" +
				"aagtgcgcatgcactccacataagcacacgtgccggaaagcgtcccattaagtatcacgg\r\n" +
				"ctagccactttctcggcggccaatgtcagagtactgtttcattagacaaatctcagacga\r\n" +
				"ccgtgctcgcgcgcgactcgtcattctacctcaaagttgacaatcgcacaccaaaccaga\r\n" +
				"atggatgatcctacaacgttgatctaccactctggaattcagtggaatcagtgaaccttc\r\n" +
				"cctatgtgtttgccacgtcagcatgcctgaatcgctacacattatagtcctcagatatgc\r\n" +
				"caggatgcatcccgtagtagcagctgtccaggattaaacattatcgtttggatacggccg\r\n" +
				"aatagtaaaaggatcacacgtttcttttcgtaaaagctctacttcccacttgtgaccgag\r\n" +
				"agtcggaatggttattgcgaccacgccgcccacatacagggtaaaatctcgtaaatacag\r\n" +
				"ggcttgggtctagttgttcagcgctcgccatgatcgggttaatgactcaaggcggcgtgc\r\n" +
				"gatcgctgataccgaccaacgacctccatggtatccataaacggtactcgcggacttaga\r\n" +
				"agctttagcgaatcgatggaatcgaagcttaattaccgcgtgtagtaactactaccgaat\r\n" +
				"ttcctttcagcaaagaagttacttgaaagagacactttgtcggtctgacgcagggtgagt\r\n" +
				"cgtaatgtaattgagtaaggatgtggaggtcaggcctgaggaagaaaaatataccttcca\r\n" +
				"gtacaggcactccgttcaagaatgtgtacatgcacaagtctaccaacggggcacagatca\r\n" +
				"ttaagatccgttgattcgagttcgcatttgccggctttcgcctaattccgttaatattac\r\n" +
				"atggaacggccaggttaccgcagcttccttagaaagatcattgcacgtggaataccggtt\r\n" +
				"acgcatgtgtatagcttttgctaagtgtctgggaggcctctataagtcttcgcttacaac\r\n" +
				"ataggacgtggatccgtgaatgtcgtgccctgtgcaagacgatacatatctggagctagg\r\n" +
				"gtgcactcactctcgaactgctcagtcaatctttttaactcccttgggagctccgcgata\r\n" +
				"acaaatgactctcctcatcgtgcactgtagggaatcttcagctacggtgcgctctgcggc\r\n" +
				"gctcactagtcaggaattaggcggtttctgatactcaggcgattacgttggtacgatata\r\n" +
				"atcaatatttaccgaataggtacaaaaaaattgatcctgtctcgaacacgagtgcctgtg\r\n" +
				"cctaccctggttattttattctcaggcttcgcgaataagccctgtgtcatataagcaggg\r\n" +
				"agaagttcagtatgaatttaagctggagtgagcgctccccagcaaattaagcacgtaaga\r\n" +
				"gtcacgtattagttgcgtggggcctgtctgtaatttaaggcgtccgtcttccttgcgttc\r\n" +
				"attttcggttgcatatggctaagccgaccttatagcacgtcgcctggtgtgaagataaag\r\n" +
				"caggactcgggttcaatttcgcggcaaagaactcatttatactgtgccggtagctacagt\r\n" +
				"ggccttctttgcgaggacgcccaggacctcgagtcgaccgaggctcagtctgcagattac\r\n" +
				"cctgtccagccaggacgatatgatgctacatctctgtatttgcatctaagccgggccacg\r\n" +
				"tgggttgatcctccttatgataattcagttttatagtccttgctctctatgttggcttca\r\n" +
				"ctacatcacggctgtgtaattaactcacggaccgattgataagcgcgacagagggtagga\r\n" +
				"ggtcgtggattcgaggtgaaaccatgtgtctaaatcataacacaaatcaaacgattcgtg\r\n" +
				"gtaggattccggttacatatcgtcgaagcctggtaacgtttggcactggattattctgcg\r\n" +
				"ggattctcgaacaacttaaacgatgtagcaccgacatagatgataagcaaacactttcac\r\n" +
				"cacttgcgtgggggcaagataatatcgcgtctttgtcatttgtggctcatctggccagtt\r\n" +
				"gccttaaggtcataaagtatagcgcctagcgctttacgagcgaagtcccatttacgtgga\r\n" +
				"tctgggtcctagtgggatgggtatgaagaacacacgaaagcaattaatccagtgtttgca\r\n" +
				"cacgccccgccacgctgatagaccggcctatgcgtcttcccacttgccccacctataagc\r\n" +
				"agcctcaaacggtactgtcggcttgtccttctatcttagagcccccgggaccctgccagc\r\n" +
				"cgttaagggcactactgcacgtgcgtgctaagacacctgtgctactcgacacgatctggt\r\n" +
				"aatgttaataagcccggtgcgatgccctccaagtcgactcaagcagcacattttgcgaca\r\n" +
				"agtacaccctaatctccgtgcagattgttccaccttctaagaaacctgagcgtgttccat\r\n" +
				"tagcattaagtaccgagtgcgaatggcctacgcgatagcccgataacccatagctccatt\r\n" +
				"ggatcactcattcctattaggtgggttgggatgccgtattcggcgggcccgctcatctca\r\n" +
				"ggttcacaatcataaagagatttcgctcttgtcgtctcgggccgctctccgacgtccaat\r\n" +
				"aaggtgcgtacagcgagtctgaaacaaatattgcgacaggtcaggaacttcacctatgtc\r\n" +
				"cccttaacgaaaatgcccccggaatagccacgatatgacatacatcccgggacatcaggg\r\n" +
				"gcgagcttcgttcgcctgcatattaacccgagggcagttttgacggtaggacccgctgat\r\n" +
				"gtaaccggaaaaaatggtgccatctttagcttcgtcctgaatggggattatgaggggggc\r\n" +
				"tgcgaagacagggtataccaaagccaacgcgtgcatcggactgcgcgcgtactttggggc\r\n" +
				"gtctaccgacattgttccaggcgcagaacacctccaacagtgcgactgggtgtgtgggcg\r\n" +
				"cggactaacctgtagagagatatgtacaaagattcttctgcgaacttctgcatcgcagga\r\n" +
				"aacgtacacgcggtaccctggtctcaagtttttgggctacgttgaggttaacccttcaat\r\n" +
				"aaacgtacccctaactctttcggacccgctatgatggtaccgtcagagctttttgctcca\r\n" +
				"gtatagcgttaacgatgacctctgtgcttccattccaccgcagagactggcgggtcgaca\r\n" +
				"accatagtacttttgctgaccaacggccaatggtcgcctaagtgtgatgtgacaccgatt\r\n" +
				"gatctcgtgtggcatgctacccattagccgtgggcagataagtggctagaatctgatgta";

		String DNA2 = "gaaacggtaccacatacagtatgcaggttgaggtgtgggtgacctccgatagaactaccg\r\n" +
				"aagcctgccccaatctggacggtgcggccgaccgtcattcatgggtaacgatcgacgcaa\r\n" +
				"gggtcctgtatcacccgttctcttgtgtaaatcaccgtgtagagggcacgacaggtacta\r\n" +
				"atcccctgagttttcgtccattcatagtcaatcagatgtgtttgtacagcgaacatactc\r\n" +
				"ggggagggacgcgtcgattggttcccctattagcgttagcagttttcaggtccctaggca\r\n" +
				"gagaaagccactctggccattgcaagtacctgattatgttatatagtttacgaatgtggg\r\n" +
				"gttggctgaaccacgtagttcgacgcgcatattttaagtgtgctccagtcaggagagcat\r\n" +
				"taggaaactggtaatgatctcctggttaaccggtcgtgaatacccaatcgaacgcacatc\r\n" +
				"aaagcgccctagcgttagctttccgcgaagcagaaagatactctagcgatagcctagctg\r\n" +
				"gtcgacatcagagttccatatatatggttggaacgggctatacaggaaccatgtcccgaa\r\n" +
				"gatcaagagtgcacgtttagcacatctaactgcggttgcaaaacgcaccatttacccaac\r\n" +
				"attttcaagctaactccaacacatttttgtggtcgactcaaagacgtaagaaaacctgtt\r\n" +
				"cccgcgatggcacgaaaccccgagccagcagtgatgaataagcgtgcgttgatggtcact\r\n" +
				"cagtgagttttacgcgcatgatgatcgacattgaatggagtcctccctgttcgccgtcat\r\n" +
				"cttcgccattagtgatagtttagtcatgccccaagtaagataaagtgctgactacatcag\r\n" +
				"ccttggttcgtgactgtctgacccacaagaccacggagttacatcctagccggatgtaat\r\n" +
				"ttcagataaacccttctcaagggacaacactaggacttctcgttgtatccgggtatcagc\r\n" +
				"tagacaagtcgatgcactttagagagagcggacgctgggaagaccctcagttagtgagta\r\n" +
				"ctaaggatttttctccggcgggttttaccattatttcaagttgcggcgtatgcatggagc\r\n" +
				"aatctacccccctctcaaccgcccacgagagtataccgatgaggctacctactcagtgat\r\n" +
				"tctcccccttcagactataactcacaaagatctgtgaaaaggaaggaccctagaaaaccc\r\n" +
				"tactactatgtggaaaccattggagccgcgcaacatttgagttccagaaagcgaatgcta\r\n" +
				"acggtgtggtcgaggttcagcctacataagtcttacgtaaaggctacgtcacttttttcc\r\n" +
				"atcacgttggagtaccaagtcgcgtaacaggcattgtctactgtctgaacgccgatctgt\r\n" +
				"attacgcggtcacacgttttgtagaatcgcatcactggatacggcacaatcaacatattc\r\n" +
				"tctctcaagcatgagtctctgccatacaacttacgaccgcgtcggccaagtataccgagt\r\n" +
				"aggcttccgccccgccctagtgcaattgacctgcagcctacgagatctcctctctgtacg\r\n" +
				"gctggtaccggatctctcccaaatccgagatccttgcagaccggcaacggtgggggagag\r\n" +
				"gccgtttggtgcaagccgttcgatagacaggcaaaagcggaatagtgagcacgttaagcc\r\n" +
				"acaaagcctgagaacgtaaactttgcaaaacaggacatttgggtatgtccgctggaagct\r\n" +
				"ccggcgcgtcacctcaggaacccaggtgcgctagaaaactgcgaccgcggttgtgctcgg\r\n" +
				"ccttgcgctataactcgagtatagtctagcgtacatcgtgaccgcaatcaaacaaaattt\r\n" +
				"tctttctcgctaggttcgttaattctagttcacacgaccgcccctttctctggatggtac\r\n" +
				"ttggacgttatcccaatcgttagcttagtataacttcatccaatccgtagcgcccaacgt\r\n" +
				"tcctaggagcgcagcgatactagcacaattgcccggtaaatctcaggacgagtgtcgacg\r\n" +
				"ccatacctgcaactcgcgacttaggtacgtcaggcacgcagtttaatacccgcaaaacat\r\n" +
				"tctgtgtgtactaatattggcagagtgtcgcgggatcagaagatacgacctgccaaagat\r\n" +
				"atggggtattcgcaacgtttcatataattaatggatgatgtccggctctaggacctcttc\r\n" +
				"agatccgttcgtcgcataccgtggagtccgaacaatacacaacccattgacctcgatcag\r\n" +
				"atgagtaactacaagttctttcgctgttcatcacccgctgagtacataaaccatataccg\r\n" +
				"tctgttgatgctccagcacccaagggtcagtaactgatagaagctccagcttcatgagga\r\n" +
				"ccgtttatgttccggggtccttccgcccatgcctttgcccgatttctgtgcccgaccgtg\r\n" +
				"acgatcgtaatgatgtccgtagtcgcctggctaagatcacgaccgcttctttttagccac\r\n" +
				"tgggacccccgcccatgtggaacgtcccaatactatggactgctctgggaacggccggac\r\n" +
				"tggacgttgaattgtacgtcagcatggtttgcagcacgttagacaagcaaagcccaactg\r\n" +
				"tcgaattactaaacaagatcccgattatcgtatccatctgatctcttgcaaatccgtgtc\r\n" +
				"gcgtatggcagcgacccctcaagcatcactccatgtgctggaaaaactataggtgcgcta\r\n" +
				"gaaaaataccgctgaagatatccctggtacgccctgagcatttacatgtagttggaacta\r\n" +
				"tctggctatctgactaagtaactgtcggtacgccactcttgtccatcagaacgatacctt\r\n" +
				"gggaagtagggatgggatccgcgagtactgaataggaagaccgcgtatataggtctgccg\r\n" +
				"acgccaggttcgggaactcgcagagtcacgtgacggtgatgctgtataccgcggaaggaa\r\n" +
				"caaagaagtctagattattctgctccagcgagacgctgcgtgtgcctcttgaaaatcgaa\r\n" +
				"tagagggcggtctcggaaagctatcttagacgaggcaacgacgacgtgtctcgtctctgt\r\n" +
				"tagttcttgcgggaccagtctcctagaaccgactgtttttggatgaaaaccgccttacac\r\n" +
				"gactgggtagtcactaagccatcactcgggaattcaagctgttccgttattcatattact\r\n" +
				"taaacatcctgagacgatttacgctttatagtcgtatagctggattcatataaggtcctc\r\n" +
				"ctgctcatgtagatgagtctcgaaggtactaagtacaggataatcactcagaggtgtggg\r\n" +
				"taggtccatccgtttgacaacctccttttggtgttagcggacccttgcccctctaaagtg\r\n" +
				"tcgtaacgaggatgtcagcgctacacgtatgtccggaccaccgatatggcgcgagtactc\r\n" +
				"gttctactttccccttgctcctgccgggctgacgggctctggaccaggagttgggcttta\r\n" +
				"gagacgctcccaatgcacgttctcagggacgtatctatgtcccatgtctgaggaatgtag\r\n" +
				"gtagtgcctctactcagtggagtcccttctggttgatccaaattaagaccaggttcgttt\r\n" +
				"tatacaagttgagccacgtggatagctgtgtaaacagaacggtgctcgagtcgtttgggt\r\n" +
				"gatctgcaccattaagtctcgctgatgtcgcatgaccttacacgctacggagcccaaagg\r\n" +
				"ataaaggtgactgtgaagcccgtagttacatgttactgagggtatcacgtacgggggttg\r\n" +
				"ctatctaataaccacgtctctggacatcacgtaccggactcagtcgatggtgccggatcc\r\n" +
				"ttgttcctccctccgataaatacgggtaaatttcgaggcgccttgatttgtcttgtatct\r\n" +
				"gtgactcttgttaattttcgtctatacttgattgtaaggccaacaggtaaacatggagag\r\n" +
				"ggagtcatcccgtttcccttcccggcaaccaaactcgagtaaccgtgatgaaataaccac\r\n" +
				"ggctattaccacagcggccttagactaagttagattgtcgggtgcgtgaagatacttgtc\r\n" +
				"ggatttttcaggtgctccgaagcagtctctacgacactaaacgagactggtaatgtgcgt\r\n" +
				"tagaaatatagcctgcgcacgtccgttgatagcgtgggtacaatttctgtccagaacgac\r\n" +
				"cacaggtggactttccctgttgtcgaagcgggaatccgaatgcaggcatacgtccattgg\r\n" +
				"gagaactactgtgaacgtacaccggacaagattctaaagggtgcagaaaaggaatgaagc\r\n" +
				"tggccggaccatcggcttagtgcgcccaaggcggcaaatcggtgccaatactgcacacgc\r\n" +
				"aaacttcaaggaatcgcgtagctaaccgatgccactgcgtcctgttgatcatttcgcggt\r\n" +
				"acaaagacgttaacgatgccaagccgatgaagtattcgaagagagctttaccagtggtcg\r\n" +
				"cgtgatacctacactttaccggcatgatggtgcagcaggcgcgacattgagcattacgcc\r\n" +
				"ggaggggcgcttgtttcggcttgcaaagaattatgaaaccggatgtatacgtaaaaagct\r\n" +
				"ttaaacggacgtttgaccaaccgagcaaccacaagctactgcatgctaacgacctctgtt\r\n" +
				"tttgtgttgtgcgcgaacattacaagtccttctcaagtatggcttcgttcgtgtaggtac\r\n" +
				"ccgccggcaggagatgagtctcgatcccgattgcccttctatactgagacagagttaggg\r\n" +
				"cgcgaagatggggcctcaccggaccggtccgggttactctgattttccttatgctttctc\r\n" +
				"cgatatgagtagttcctaaaacctagattaaagtcctgataaaacctatcgtttttgtag\r\n" +
				"tctgtctaaactgaaccttgtagtatttaaataagaaggcgttttcaccccggcttacaa\r\n" +
				"ccttgctggacacccattgattgcagtgggacggttttccgtagccttaccacgccttct\r\n" +
				"tcttaagggatatacctctctgccatttggaaggtggcgacatcgtacaggcttaaacgc\r\n" +
				"cagactatctatcgaggcttaaggctcggcgccagaatgctgtatctagctcaccccctc\r\n" +
				"atctccttggggtattcacgccgaaattcgtctggacgagatgagataatcggtgcgcgt\r\n" +
				"tatttacttccgtctgtgcaccgcgctcgcaagccaggcctgctacctaccctgaagcca\r\n" +
				"gacccctcgcagagcactccgctggcggctacaccgcctctgtataacaaacataaacac\r\n" +
				"gggcttactgcggcaccttttgcccatttcgttattgtcaaagctctacagaccggactg\r\n" +
				"ctggctgaacgtatatttgtacgtcaaggcgcgaatgcgatgcaatccctttggttagtt\r\n" +
				"ctgacacggctctagctaaaagacccgtcgtggggacccaaagaattttcaggaaatgct\r\n" +
				"tccggaaaggtctctccagtcgtcccattgtggtggctctgtacgccttccgaatcaaga\r\n" +
				"cgactgatggtcctcatagaagcccgacacatacggtagagcaaggccttaacgccaccc\r\n" +
				"atcagccttcatcactggtttcattcaaactattgtgtcaaactggagggggtccggtga\r\n" +
				"tattaccatcataacgtggcttataacccgcacacctagtttagtggatgcgtattccgt\r\n" +
				"gggctaaactgttgcgataaagtccgtaaacataagaaaattggtaattttgcctgtcat\r\n" +
				"aaaacaatgggtacttgaaatctctctagatagtagtctcctgccctcttccggggaagc\r\n" +
				"tcgacgcgaagcggctcgcgctcaaaccacagtggccttatgccggctcacaaacacctt\r\n" +
				"caaaacaaacaggtggagcccgtaaatatttaccgagtcttcactgttaccaacggaata\r\n" +
				"gcgtccccacactactagtggacttgcttactggataagaaaattgaccttactacttga\r\n" +
				"gagaacgctcccgcaggtagatgccttcttttttcgtcttttggttcacttttacaaggt\r\n" +
				"cggtcgcataatatcctgggccgagatcaaaaactacttaacctcacccctagcacaccg\r\n" +
				"accataggattaggcagtcgttgcacgatgcggagcacaacggggctcctacgatgcttc\r\n" +
				"ccatccatttccgacgttaggcatgagagtctgcagagcgttctggtattctctggctgt\r\n" +
				"acgctgcctcgttttcgaatacgtatacgaatgtcgttataagcacacgttcgaaccggg\r\n" +
				"acgctcccattttctcttggaaggatcccttacgccaggaggtccaggggtatgacaccc\r\n" +
				"tgattccgggagcccgaattattcacgggatgcggctgatccaatgcgttgagacgtctc\r\n" +
				"agaattcacttaggccaccgccagcagacccatgcacatttcgatgaaaacgtcctatca\r\n" +
				"taatagctcaggtgtatcgtgaacgtcctgacaccgacaatccatgtgtcacttccctag\r\n" +
				"tatgttcgaggtgcgaagaaaaataggctctacgagtcatcggtattaataatatgcacg\r\n" +
				"aattcccccggcaccggggcaagacgatttgtatgctggtcggctgggcgagctaagtac\r\n" +
				"tgcatttgcccgccgggggatgtcacgtgtttagcataggttcggttggggaaagggctc\r\n" +
				"aacctgtacaaggtcgtgcctgctggagtcattgacgtgtaccatccaatggcggtatct\r\n" +
				"cgaactgcttaagtccgccgctcttagtgatagacccacgaccgccgcaaccgatatgcc\r\n" +
				"atccttaagcccttgccattccagttacgtagctaattcagggccctaactacgaatata\r\n" +
				"gctcacaccaacgcctttagatacggttatatggtgaatctggacctacggacgtgaacc\r\n" +
				"tgtttctgggtggtgttggattactcggactctcctatcgggaacacgtccgaattcttc\r\n" +
				"tcattcaaagcatagccccagagtaaggaatcatcttatgtgtctaaaaggtacgagaaa\r\n" +
				"agacgaccgctctcttgtggccgacaactctaagcatatccaccacctgctcctatatcg\r\n" +
				"ttaatcacctgggttgagttgatctcagtacgatttaaagttcgtgttctggtagaccaa\r\n" +
				"ggatcgcgaaatatcattcctcccatccttttgtggtcaccgcctgtgcctttgtgcact\r\n" +
				"gttaagtgtgtataatcattgttcttgtcacataagcagctaggatgaacctggctactt\r\n" +
				"aattttggaatcgccgggccccgccgtggatatacaggcacgtcgcgtctagtgagataa\r\n" +
				"ggaccctgtaggaatcgaggcgaaggttgcggcgggcatgtcgatgccgggtatgctaca\r\n" +
				"ctatggacccagaaaagcatatgatctatttgacagtccatcatatccagaggtggccct\r\n" +
				"tttggcttcaacgtgattttgatcgtgtgtagaagtcggaacaggaagtgacggccacgt\r\n" +
				"taaggcgtcgtccggaccactcccataatggttgtgcagttcaacatttggatccggcgc\r\n" +
				"cagttcctaactttcaacactagcgcggaaagcgtttacatcttcaagaagcaattgctg\r\n" +
				"ggaggcatagaactaacgtcgattatcagtggagatactaaggtgcgcccggcctactgc\r\n" +
				"tataggcgataggtttaggtttcgggacggcctattcagacgttcacctttagtacggag\r\n" +
				"aactctgccttgactaactccggctaatacataaacgggtaccctcatcgacaattcgta\r\n" +
				"gccctgcttatcctacacacgacgggcgatgtgctcaaatgggatccgctagtgagtttt\r\n" +
				"cggcagggaaatccatatactagcaaatgcagaataggcggactagataataggtcctgt\r\n" +
				"aaccacaaatcgagagatgttgattccttctgccgtcccatatgttagtgaacttagctt\r\n" +
				"ggctagcatcgatggattaacagcacagtaccaactgttaggagcaaaatcacgcttgtc\r\n" +
				"gcggctgaactaagcaagaatatcacaggtgtggtaaaacttcgtcattaaccttggaga\r\n" +
				"ggctaaccgcacgtaacagttaaccacaacccgcatcagcatctctgacgatgaagtacc\r\n" +
				"tcaagaaaccacttgatgctgttccatgtatattattttggtgtccagtggcctccccac\r\n" +
				"tacctgaacgtgataacgatcgaaaatagaacgtagtttatcattgagcgctcgagtcgc\r\n" +
				"cttgatgctccttcgcacggggtatgcatatacccaaaaacataacatttttgaacacta\r\n" +
				"gtgctagatggttataaatatgagagaccatatgagaccccaggtttgctgacagaggga\r\n" +
				"aacctctggaggttggggtggttccagatatagagataccgcccgggatacacttaagag\r\n" +
				"gtaaaccggcacactgtggtgccgcagcaaaaccgagaacgtacattcgttactagaatc\r\n" +
				"attcaggacacaggccctgattccctaaagggaaggcgacgggtgacattgcgtcgacac\r\n" +
				"gttccgtcactgtgcccaagtgtcgacaattaaggtttttaggatccgagcgttcagttc\r\n" +
				"caactcgtccgcggaaaataggtatgctgtacttgatctcatcttgggccaaggaagaag\r\n" +
				"tcatgtatagactccgcataaggttcacggagtcacttctcgagcttcctacggagtcct\r\n" +
				"gcttcccaagaagaaaaagtttgaatactgattggaactgtacaacactcgtgatgtacg\r\n" +
				"taattgcgccgtagggactgaatagagcctcattggcgcatgggatgggtcatgggaagg\r\n" +
				"cttttttgggacgtgatcggttcatccgtctgcatacggcgcctcaggagttcagacagc\r\n" +
				"ttgtacctcggaaacggagccgtgtcaacaggggcgaaagcgtgccctttaacaggcact\r\n" +
				"tcggtaggtggattccccggctcacaaaacgctaaatgcttagactcgtctgtcgtgtgt\r\n" +
				"ggtttgttacatcttatggaccgaaagaatacgtgtgtttcctcattagacagagccttg\r\n" +
				"cgaggtgtcgctcgtgtacacgagatcacggagaatacgatcgccatgtaaataagaggt\r\n" +
				"agacttgagccttatggggttggattgtgaataccgagaggtcgcttctgacagcgttca\r\n" +
				"atctactcttcacgatcgcgctcatagtatgaacttggtacccccagcgcacctgatata\r\n" +
				"tctactcacctggtgtcgagccaacctgaaccacaagccgcccccgagccgttctacatc\r\n" +
				"tctccagagcgtccgtatatagggtcttaatcgaatgcggctgtcataagtgatacatac\r\n" +
				"ggattttgtttgaggactaggagccgcgttccgcccctctgcacgctacagactgttctg\r\n" +
				"gcattgaggcgcgctaaggcggttttaggcaatctcggcttatcgcacttgatccccgct\r\n" +
				"acagagggttcgctacacgctattacgcgacgccgaagggtttacatcaattcacgtgcc\r\n" +
				"gaatatctcgtatctaaccatcaagtgtagaagcacgctaggactcagcaaggaacacgc\r\n" +
				"ccgacgattattcaggtgaactatcatcggtcttcggcatcgaggtgactcggctctaac\r\n" +
				"acatggaggggctcacttatgatgcgcgtcaaaccaaccacgcgggttgggttgatcacg\r\n" +
				"tcggatatggaaggggaacacacgtagggacaatccatacatgactcgatggatgttgcc\r\n" +
				"tattggtgtgatgcagattctgagatcaaagtgctaccgagggagatggaggggcaaact\r\n" +
				"cttcatggccaatatggcccctttaaactttgcatcgtgtatatctatgtgttcacgtgg\r\n" +
				"cctgtgcgctgcatggaaggctatggacgggtaaaacggcgagattgtagagcgattgga\r\n" +
				"accggtcgaaatctcggaagacatttcctgattaacgcctaaccgtatccaagtgggttt\r\n" +
				"tcttcgacaccgtgacttagcgacccagtggcgaaaaataccggtgatcacacgtcggca\r\n" +
				"cacgcatctcaatggcgtagcatgcatgtatgagggctagaagaccattgacagagatcg\r\n" +
				"tcctccgcatgttatacccacaaggggacaccggtgcgccatcaacgtctgctgtgcaac\r\n" +
				"tcagtctgaataaggttggaacggagagtagatcggtgaactattgcagagggcgcacgg\r\n" +
				"atgcccgatccgctccgttgcgactaaatgcttaaccacgccacgtttctgttgcatcgg\r\n" +
				"aaatcgcccgtcatgtaggcagagttgacgagtgtgcggtgtggggttcgggccagctgc\r\n" +
				"catcgtgctggctgtatcattgtttccccgacgtggtttggtccctgaggtcctgttgtt\r\n" +
				"gtaaaggcatcatgacggcacgaacctggcatgagcgccacctgaggcgatgagtgtgca\r\n" +
				"cggactagtcacggcttcgttgactcttcagcctcaccgtgatctgggtgttggtaatgt\r\n" +
				"gatcatctggagatatattgactgcagctaagtgtaagcagctcatagtcgcgggcacca\r\n" +
				"cgcaactttcgagggattacccgggccgcgtatcgcaacaagtgcctctatcttccccgt\r\n" +
				"caaagacttgaccgttgggacggtgccgtgcaaaacgggctaggacatcatccactatgg\r\n" +
				"tagataatttgtaatccaactcaaccggtctgtagattcgagtggtgtcaaaaatgacag\r\n" +
				"gtcgtgacctgactgcacacccagcgtatgaaatcggtgtgacaacacaccccagcaacg\r\n" +
				"attgactgcgcgctaataaattcaccggtaccgcaaggcgtgcacggtaagcattggaac\r\n" +
				"cgtacagtaaagttttggttaccgaatgtccaattaccaagagccgggaacccacagaaa\r\n" +
				"gtgcacgaagattggatgaccagtcaatgttaagtccgtcactcgggagaagcgggaagt\r\n" +
				"cgatggtttcgacagtttattcttgacacacctgatgtgtccgggctcctgactctatgt\r\n" +
				"cgcggtgaaggtcatcgctgggcaaggttgtggcattagttcgacgggtaaggcattgtg\r\n" +
				"gtatcctcgcaccactagatttactctcaggaccacgggtgggtgaagtttagtcgacat\r\n" +
				"ctgcgaattacacgctcaggtcgactagtgcggatcttttactgcacgagtatgcgccca\r\n" +
				"ggcaataatatcggagccacgcaacttttccctgttagtgatcttaggttgattacccca\r\n" +
				"gtataccaattacacaccctaggcgctacgggtagttgcggtgccttgtctgttgctcca\r\n" +
				"agaagacagttggctatggatgaagattctgttctgtcgcgattcaatggcggggaccac\r\n" +
				"aaatgcccgcccaggaacgagtcgcctggttcaagttcattctggtataccaatcgtgtc\r\n" +
				"gatagcgttcagggtagccatcattagaccgtagaacggcatagaataccagtctcaaaa\r\n" +
				"atattaggcgcattgggtgtggagcccgtaatcagtttcatgggatccgtgaaccgggtc\r\n" +
				"cgccacctaatatcatgaccgcaaatctcagatgaccttgttcagccggcctaggagccc\r\n" +
				"gaacaggaggagacaggctgtagccgggtaggagattgacaatgtgcggctggttccccc\r\n" +
				"aaataaattgaagcaagtcgcaaagtcacgctccgaatataccgcgaactcccattgtga\r\n" +
				"ccagctattaagtggaaccggtcttctcgggtaccagtagtcaggtgggcgcattcacca\r\n" +
				"ctgcgaatgctatgcaacgacccgtctaaatttcgaaaggggacgtgaagcgcaatccca\r\n" +
				"aataacccctcgcacaagggcaaccgagtgtatgcggcacgtggcgaacttgtagtcacc\r\n" +
				"tggtcgcgttataggccaccccaccgtaaaatggcttataaagctagtgtttacccccca\r\n" +
				"agttataagagtttaccgcgactcgagacgtggatgtagcctcaggtcgattcaggacac\r\n" +
				"ccccagcacggatttagatagggggcttgccgggtgtgcctgtcatcccccgtgccaaat\r\n" +
				"ttaactaacccagggtttaagggtgcttggttgagcatcctcacgcttaccccgtatcca\r\n" +
				"ggccttgcgccagattttagcagatagatctgaaaaaccattgttcctatgcactaccaa\r\n" +
				"cactctcgctaagttaatcccctgggaagccaagaacatccacaggggctgtacggctcg\r\n" +
				"cccaaaatagtgtgtcttgcgttaccgtctaccacaaaggcacacttattacctcacact\r\n" +
				"gtgaaatacagtattaaaaagtatgtaacaagaggtctaaacggcattgacttgcccgct\r\n" +
				"cggtagtttcggttatgccgcgcatcgtacaagatggttctttgacgagaggtgttccat\r\n" +
				"atcactggcagatttgcaatcgaattgatactgtgcgttagtctacgagaaggggaaccg\r\n" +
				"tggtcaatgccgctgtagtttgtgacagtaccaacttcatcgaagacattattttggcac\r\n" +
				"gctcagctgatccgagcatttatagattgccctatcataaaccctctgcgcgcattatgg\r\n" +
				"tgttatagccgaggatggccatcgaacgggtacaaaatcaaaggtcgtcttgagcgatta\r\n" +
				"tccgaggtacgcgattagccatacattaaaggcatttccgttgtgcccgacgacatgtcc\r\n" +
				"aagcgcatattcaagatccccagagttatcattcattgcttcgcttgttaagtaacgatt\r\n" +
				"cagacggacgtctagcgaatgacagacgccaatgtcctgagctgatttttatcggtcccg\r\n" +
				"aacaaacagaataggcctgttccgatcaacgatcgcggttttcaaaatcctgaagtgcct\r\n" +
				"atctatctgctctagctcttagcacagggttcctgctggtgggcgggatctcgtatcctc\r\n" +
				"ctaattggcgttcagccgccctacgtggactgcaggcttcagcccggttagtaagatcat\r\n" +
				"tctcagcgagcagttctcctacaaactcatgtctcaggttagtcgagattaaacattact\r\n" +
				"agttacgaccttctacgaaggtcacaataacctcccctcctgtcaaaacgaaataatacc\r\n" +
				"tcggaagttttcactgacgtatttcaaccatatgctctctgaattatgatgctaggttag\r\n" +
				"gtcagccttacttcaggcatctagtatgacccgggacacggacagtgttttatactgtgc\r\n" +
				"acgatatctcctcgtttccataaaggcagagcggaagacttatgcctgatatgctcaatg\r\n" +
				"tttacacgatcgtggtacagatcatgacacaagtataaggttctcatgtgctacaaaatg\r\n" +
				"cctacactttgctaggcgagcagtccatcccctaagagctcagctttattcggctaacag\r\n" +
				"cagcaaggattaaataactcggtatgccgtggggtagaaccgcactacacctggcctact\r\n" +
				"ggatggacgaaggagaacgtcttgatccgaattgatgagtcaacggggcacgtctttcca\r\n" +
				"tatctagtcgaccacttctcttagttgatagatacaagttaggggtgatagtcgctcgac\r\n" +
				"ttcccctaggcaagaggtttcctgtgcatgaccaaaagcaaagaggataagacttcacgg\r\n" +
				"cagggtctgtagatccatcattattagtatgggattgtgacaagcgtcgtctcccacctg\r\n" +
				"gggacagtggtcaaatgagtattgtgcgtgttttgagcaaatagaaggaaaaattgacgc\r\n" +
				"gcaaacgccgtgtatgtttaaacgcgtaactcgttgcttcattttactactttactagca\r\n" +
				"aatggccgatggggtagcaatagttatctgcaaatttgatactactagtgctcgttgagc\r\n" +
				"gactacaagtacgcaaccccctgtgccaagaattagtagaaatagccgtccacaaacctg\r\n" +
				"agatgcctcgctggacgttatatgctctatcggacttgggccactcttaccttgcatgga\r\n" +
				"ctgtcgctaacaggcccgaggaatagaattccagacctacggtgaattccaaacttaaag\r\n" +
				"caactcgacggcatcatctgtggtttaacgttggatatgtaatccgcgccctcattcccc\r\n" +
				"atctgttatcgttttttcaagataggtctggcgttacgcacgcacacgagtctttagtaa\r\n" +
				"tttgatcggtcttaagtctatgtcataaaatgcatatccacaggttatcactggaacggt\r\n" +
				"taaacagcctgccgaataattggtgtaaaaagcacagatcttcgaatgtcaagctatctg\r\n" +
				"caccccccgtagacgaataacggcattcgcttatagtcgcccggtgccccagcttcaatt\r\n" +
				"caagtgcgttaacccccaaagctaaacattgtcgaactccatcatgaagcacgtccatat\r\n" +
				"acgtacgggttatgcgcagagggtggcacttactacacttatctgctgagtaagaggaat\r\n" +
				"ggcgggcctgctgctgtctacccattagtcgtcttaacacaccaggcttcgtctgatgat\r\n" +
				"tggagcctcagaatggcgtacgagtaccctgtgacaccgaaacggggagacacagacggc\r\n" +
				"aggcacctttacagtacactgtcatcttcggcagcttcactcgggaatatagcctattat\r\n" +
				"cgtttcttatagtcaccttccaccgacgatgaacttggttggtcatcgcggtgacacggt\r\n" +
				"tctccatggcgaccaggaccgggtacaaggcaaccgaagttacggtaggacgcgccggga\r\n" +
				"tcggcccatacttgatccacaactgttcccatgtaggacagtgacctagatgtctgccca\r\n" +
				"agcaactcttctgtccggcgaatcctagctgcttacttgaggcgactgtccgcgcagtgt\r\n" +
				"tcacgtaacccaaagtcggggttcagatcgcctgagttttgtctttgctatctcgctgtt\r\n" +
				"aggggccaaagcgctgccgtaacatccatggtggtctaggctttctgtgtgagccgctta\r\n" +
				"cgtcttcctaagcggccgcaggagaagttagcagatggtttagacacgccagggacggga\r\n" +
				"ctggcgcgtgccctatccgccataccgatctttagatcacagtttccgaatctttaggca\r\n" +
				"tgcctctataatatgtaatctgtgcgacaaccagccgcgtcggctactctaacccgcatc\r\n" +
				"tggtgcttaggcttattgcgtttgctgactgagtcgacacctttcctttaaactttcggc\r\n" +
				"gagaaggcattattacatggagagttgcttcccctggtaattataagtctgggattaccc\r\n" +
				"agtggtataatgccccgtccctggtgatacgtttgatcaaattattctcgtggcatcgtt\r\n" +
				"cggccataaacaatgagatctatgcagcggcgatcagacatctggccaatcttgggctaa\r\n" +
				"tgctcaattacaaaaactgggaataccggacacgggaacaagcgccggaaattagagtac\r\n" +
				"tagtcctatattgagcggtttataaaagagcagccaggggtctgtcaccttcgtccggcg\r\n" +
				"gcaacattgcttctctctcgtcttttagggtcgcgattggaaagaaggaatttactgcat\r\n" +
				"cagtctcggaaaaatgtgcttcataatcagctcagcgttagtgcataggcccgtcttgga\r\n" +
				"ggcagagctgtagcatgtatcctagagagcaaaagggcgacagtggctttggaaacttgc\r\n" +
				"gcccgatcctgctgagatttttgaccaaccgtacttcaacagtatggaaatcccgtaccg\r\n" +
				"atgtgatcggcaggactcctttaaccggttctagcatggtaagaagtaatcacaatcctg\r\n" +
				"cacgtgggcaaatcggacaggaaaaatgagataccaactgcgagtggggcaatccagcag\r\n" +
				"gcatactgatctcgaatggttaggctctctcgaaagcccaccttttaatgggctccttgc\r\n" +
				"gggcaactagaaccgttgggggctttcgcttcctactatttggtagcgtctttgatttgt\r\n" +
				"tggcggacgaagttagagccgaacgatcccctacattgtctgttcataacacattgcgct\r\n" +
				"atgcgaagcttcagtaaagctgcgatagttcggtgtgttcaacctacccccgaaccacga\r\n" +
				"ccctccgtaagacagcgtgtcccctagccctcttctcggcgaaattttgtacggatcacc\r\n" +
				"ctaatgcataccatagtggtgtcgcaatccattcacctgctaaagctcagcggctgaatg\r\n" +
				"cacgatgaagtagagtcgacgtggtgccggcggcccgtaattagttgttcgactatgata\r\n" +
				"cactgaccagcgcaagacagagccacctgagcgtcatgctcttgcgaccacgatcaaaaa\r\n" +
				"cgccacttgtttgcactgattgcccgtaaaactttttgcctgtcttggggaccaaccgag\r\n" +
				"aattctgccaagcgcgaggctggggttaacccttttacttttactgtagggtggtagaaa\r\n" +
				"atcccctactcagtcctcaggagcgtccacaatcacgtggcgccgtcataggcattacgg\r\n" +
				"ttactttgtgcacgacgcacgagaccggctggcctagcccaatactaccgatcattccac\r\n" +
				"tacaaagtgtgccgggtaaaagggccatgagttgaacgcatacgtaaaacttcgatactt\r\n" +
				"aacagagtgaggcctacagcggtggccattgaggagccggctaaattggaaatcgtagtg\r\n" +
				"aaacctaagactactcaatcagatcaacgcaggagcgtcgcggaattaccgtgcacgccg\r\n" +
				"tctctcgcgggagtagggcccaaacgaagtgctctatttgtcacctaatgtccgtctgag\r\n" +
				"ttgtcacttgggcataacctaaataaattacaatacaggggatccacttagaatcttagc\r\n" +
				"gcggttattgatcggttccgagtttgggtgttcccaggtgttccgatctaaaaacgacgg\r\n" +
				"cttgacccaaggtcatcttcccgcgtgaaaaacgcatgcgtgccagatcacaccttttgt\r\n" +
				"tacctggcagctctaggatgacgtgcgtttgcaatctagtccctcagggactacttgacg\r\n" +
				"ttggtagagtcactgcttaacatcgaaactcaaggagttgtgacagaatcgaggggggat\r\n" +
				"ttcaatgttaggccaggcgaaccacctaatgtagcgcgcactgctgggttgcacatgaga\r\n" +
				"agttgtgaggcagtaattttcacctgcgctaaccgagtcgtggtctagcacggagtaacc\r\n" +
				"aaggcttcggtggaaccttgggtggattccacgccatatttctggcttatgattcttcta\r\n" +
				"atcccttccgttcattagacctggtgtctacttatcgacacaatctctgtagttcgtaag\r\n" +
				"catgttgttcatcaactaacgtttgctgtcactttaggcacaggcgcctgatatgattca\r\n" +
				"tcagacgcatcgactgtgcgttcaagagtcattagaactgaccccataaggggcgggcat\r\n" +
				"aagctgggttctagtggtttgtcacgttacatccggcgcattaagtcgctaataacgaag\r\n" +
				"tctgaaatttaggtccaggagagagttctgccagcagtcccggatgactgcacgataggt\r\n" +
				"gtaactttctcggcacaaggccgtctattacgagggcctgccatgtggattacgaggcaa\r\n" +
				"agtctctggggagggcacgctcggttactccggcccagctctaagtgtcactcatcagcg\r\n" +
				"cttcgcgaatttgagacagaaacaagattatactgagcggtatcaatgtatcgcccaggc\r\n" +
				"ctcttaccttccccttggctaattagccctgcataagcgtgtaagcagtcctgaccatgg\r\n" +
				"aaaagtgagtcagcatagcagccgtagatgactaacctgtatagtgctgtcgccaattat\r\n" +
				"acaggaagccagaccagatttggatatgcctcccgattgaatgactctacttagtatacc\r\n" +
				"ctgcgcggagatggatcttcgtcgctctggcttgaacatagttgcaccactcgaatggag\r\n" +
				"tgaagttttctcgtgagtatttcattaggaatggtgtagaggcctcgcagtgtcgaagcc\r\n" +
				"attccccaggttccacacgacttttcgagatggttggcattccgcccaactcaaagctat\r\n" +
				"gcaaggaagaggtctaaacaccgaaattgcataatgactaattacaagtcgcttactgga\r\n" +
				"ctgccactctcgttacactaggctcatggccataagctacagtacggtcgtaatcgatca\r\n" +
				"tgtatgccttgcgcctagcgcaaccaacctggtggaaaagaggtggccgtaatcactggt\r\n" +
				"ctcgtctgggctcgaggttggcgtaaatactcgtcaaagatacacctgatgttgcagcat\r\n" +
				"agtgcttttctcagcttctagatagaaacggactcccgatatgttagtgcataggctatg\r\n" +
				"gccggagagctacaatcgaagggccgggtaatttgcctacgagttgccgcttaagcagat\r\n" +
				"ccacaaactctactgcacgtccgcggaagggtcgacggtcactggtttcttaagtttcta\r\n" +
				"catcttgccgctaattagtgacggaaggagtgcacctcccaaacgcgatgctcgtcttat\r\n" +
				"gttttcgtaacattccccagaatctctctgtttgaagcgtctttcatttccttatggccg\r\n" +
				"ccccccctgatcaagaaaatcctgcaatgtattgtagaagactaaaaacctagtgactaa\r\n" +
				"ctcactgtcatatgtatctggtgcaactcatggagaaccctggggaaggcgtcgattgat\r\n" +
				"aggggcccgccattgggtagtagaggggacagctggggcgacacaacatacttgacccga\r\n" +
				"agcgctccaataagattgttagtaatttctaaataactgtccggcggttcaaatgtgcgc\r\n" +
				"tctccattaaagttctacggtttagtgggtccacgtaaaaatcggtggttgaggcgcagg\r\n" +
				"tctgctcacggatcaaatatcaaccggattctgtaggcgtcctgaaaatgttgccgaagt\r\n" +
				"gcctgtgtattataatgtaaaaaaacctgatcgtgtttcagtagacatccgccgtgctgt\r\n" +
				"gcaaacagtgtcaaccagtgtcgggcccgtatagaagcatccgggactaccgtctagaca\r\n" +
				"acgctctttcggaagatgacggctgtactaataccgtaacaggccggatacacatggagc\r\n" +
				"ccctgatgttggaggttaatccttttgccttcgcatgcaggaggccttaccggttttgac\r\n" +
				"aaccctaaatatcttcgaccggttagagggcttcttgcttttcgtaagcccggccttttt\r\n" +
				"cccaacggggagcgcaccgacaatgcataggcccttacaacacaccacgacagtgagctg\r\n" +
				"actcgtaaatttctgcaagtgcagacaggtgtctcgagtatatgtgtgactttcagctcc\r\n" +
				"cgttaaaaaagacaatacatcatagggattattcgtttcctggctcgatccaacgctctc\r\n" +
				"actaccataaaatttcctgtgttacgagcacctggccggggcacggcgcatatattcccc\r\n" +
				"ttatccgtctaaatctatcgtgatttaaatggcctacccttctagactaatcctgattat\r\n" +
				"actgttcagaatgtggccctgcttctacatccagcaaccgaagcactatatgaatgaaag\r\n" +
				"ttctaaagacggccgggcaacgccagatgacgatcatttacgctatttcactacgaaggg\r\n" +
				"ttgcaggttatcacgccggttgtttttgtatagctaattttcgctcttgttatgcacgag\r\n" +
				"atcgcgcataaaataccctcgctgccccatacgaagcgagactaacatcgagaaagggcg\r\n" +
				"tctgaccttcagagaggacgatagcacgagatgcttggctcgacacagttgacatacgag\r\n" +
				"cttaagttgcggaacactagacgaccgtatagccccttgaaaacggctctgcaaatccat\r\n" +
				"ccattgttctctacgttaagtcggtatttacaatcgggacctcgaaaacgctagtaggtt\r\n" +
				"cgtcaagcggcagtagaaactgtatcatcaggttgcgggtgtatactaagtcccaactcg\r\n" +
				"gtacgagccttactgaaaacctgttcctgtgcgccgtcgtcactaaggataaacgagcag\r\n" +
				"gagtgcatctggggattcaacttctcaacaacgacacggccaataggccgaggcgaagct\r\n" +
				"agtggagcatgaggtgagtggttcgtttggcgccgatgcgtatcgtatagaagcctcctt\r\n" +
				"acaagatttcccagaccaatacgtacgagtgcaaccgttaggtagcatcccccaaagagt\r\n" +
				"tgatactccgcgggttcgccggtcgatggacggcaatatggtaaacctagacaggcactg\r\n" +
				"gcgaaggcttaaaattactacaggaatgtttcccttcggtcgccgtaggtgcacgattgt\r\n" +
				"tacagtactcgttgcgtctagcaatggcctgggaccgtcgccgccaaacgtaccgggaga\r\n" +
				"tggcttcgtgctcactgatgtcgatctactggatccattctgtttagctagcctttgaaa\r\n" +
				"aagtgcgctttcagccagcccgtaaattatgacattgttagccaatactgaaactcatgt\r\n" +
				"gctgtgtccgtggcgctacacgttgtcggacatttcactatctggacagagtccagagcc\r\n" +
				"atttcgtcgtatgactgacctttgcctgtataatgacaaccaggtcagcccatgtaataa\r\n" +
				"caagaccgaggttcaaacatatggtggcctattgctctgtaagagaggcttaccaattag\r\n" +
				"taaaaagaaccccttctatagatacatggtcgagttgaacgtactccttgaactgtctgg\r\n" +
				"cacataagaggagccttgaggagagacaagtctaactttacgatatttttcccaacggcg\r\n" +
				"tagcggattagggcgtcacgcggaaatttgcctggccacggcatctccataaaagaatat\r\n" +
				"cccgcaggtccagcgggtaacataatttgaccgctggcatcattaacgaagattggagac\r\n" +
				"gggaccccttcatattcctgcagctcctctacgatactgtcaggcccgtcctttagcgac\r\n" +
				"gccattatgttccgttagggtccttccagggggcaaatctcaaataatctctaattaaat\r\n" +
				"ccgatgttcaggcaaactaaccgccataggggcgggtggtagtctagcagaatgttttcc\r\n" +
				"tgcgcatgacttttgtccggaccaatcccagaaacaagtagcacaagccggacctccgag\r\n" +
				"atatggacagaccccgtctctcgctggcgttccgcccctttgagagggctggtgtgggag\r\n" +
				"cagaggcttatttcgtctgggaggtatagcgtcgcgaactccaccgtcctcttccagggg\r\n" +
				"gagcttcggtctgagaggtcggtctgggaggacaaggtgtacgcgtgacattcgcaccgc\r\n" +
				"gttacgtcgagctataaaggtccgcctcccttccctatctggcctcgagctagtcgtccg\r\n" +
				"gaagcactggcataggcgacccttttttggaggtccctcgacctatgccaaggatgtcac\r\n" +
				"aaaggctcgatcacccacactgtaccattgcttatcaggggtcccgaaccgcgtctacag\r\n" +
				"gctatacaatgaccgaaacatcgtaccatttacccgtaggtcgcttgcttgtctctgggt\r\n" +
				"taacaatagtcggaagtcgtctctcgtcgggggtactgcgcttacctcttgatgcgttcg\r\n" +
				"atttgcggagcactgtcggataggagggttcgactcgaaccccctaccatgcaagaaagg\r\n" +
				"tattcgcccccattatccactctccggatagacacacaatgtcctgttaagttccgttac\r\n" +
				"accgcaataccgggctctagatttagtggtgctagtatgccgttgggtgagctggaaggc\r\n" +
				"tgatgagaagtggaaagtctgtcggtcggcaatatcattgtccagtccacgatgcttcta\r\n" +
				"gggaggaaggagaatgacccataagcgcggtcctttgcgggaggtagacgtacggcatgc\r\n" +
				"tatcttcaacgaccctgggcgacagaatagatagctgcaggaggctcgagtggctaccgg\r\n" +
				"acatctctcatagcagaagacggcgcctggatcgattcgaaaccccaacctccccattta\r\n" +
				"cgcacggcgcggcgaccgtatggcggtgcgggaggtcgcgccatgactgaagtctctact\r\n" +
				"catgcggcatcacctctaagttttatcaagtcctccgtcgcccataacaaagcaaggtca\r\n" +
				"atcttgcctgattacataaagttacacagcatcagatccagtgcgcccaaccacaacgcg\r\n" +
				"gtatgagtgcctactgtttgtgattcagtgtgcggccggaacgagtgatggggataggtt\r\n" +
				"gtgaccatcccatcgtacggtccactacgctaccgtctatgagcaagtggacatgaccaa\r\n" +
				"tataaccgagttcgggacataattctcctcaaccgcacaccgactgggacggacagagct\r\n" +
				"tttatagggaatcatgaccgcggtacgccaatgctccttgccacccccctgccttcagga\r\n" +
				"cgcctcgcagggtaataaatttcaagtcgagggctactaaggcggtgtcagtgtgcacta\r\n" +
				"gttaactaatcgtaaccatcgtatcacctgcacggaggaacaagctaaccgaggactcgg\r\n" +
				"gcgaaactctatcctcgcccaattcctccgcataaatgatgcccaagtagtggaagtctt\r\n" +
				"ctcggacggagagcgactgaacgttatgttgttcttttcgaagtctatagggaagtttta\r\n" +
				"taaatctgcctatgacaaaagtacgccttggcacctagatctccaccgtgcaaaattact\r\n" +
				"ataaccagggtgctggcgttaacacacttgcactacacgtggatggcatcccagaggaat\r\n" +
				"tagaagccagtgcggaataagtccccacattgttgtcagcccattcgtaattagggaaaa\r\n" +
				"agtgcctacagcatccgcgcttgatatcgtctggcaggccaccagaaccgtgacgacgac\r\n" +
				"cagtttcggacacgtcccacctggggtatgtagttttgtcacatagcgttccacttggct\r\n" +
				"ggaacctgtttcaatgactgctggtcacttgcacgagtacagaagagactaacccccgta\r\n" +
				"tcattactataaccaaaccgcaccttgttctgacctgtcatttcggttgccgtagttgat\r\n" +
				"tgcacgtggaaattgttccgcgacacgtttaatgcttcgatgaatcgcgagggaatgcac\r\n" +
				"gaagcgccaacctcaactttattgacccgtgtgcccgagtcgtaggggtagttgatatgt\r\n" +
				"cttacttgaaagagaacgggatctctacattaataaacgggtttgcgtaagttattaggt\r\n" +
				"cacaactaaatgtatggccgtaacatgcaacaggggcatctggggtacttgtgagtacta\r\n" +
				"agtgtcaatgtcagcttggtatgcacagcccgctgactgtttatgcggtgtcctgaatag\r\n" +
				"acgttaagttacatcaggaagaagcaagactcgacttactcttatgatgcacaacactcc\r\n" +
				"acggccggttgagcaacggcctacaactggtgagtgggaggtaacattacagagcccacc\r\n" +
				"ccacgaggcgcaaacgtgtattgagcctcgtgttctttccaacctgatggtggatagccc\r\n" +
				"tgccagtttataggtcccttaaagctcctgccggagatattttttatgaaaggattccca\r\n" +
				"agtgagcgcgccacgtactgttctaatgggctgcgtattaagtggagcatgcggcccctg\r\n" +
				"cgaattgtataagcggccgaacaaaccaaccctacatgtaaggatggcattgacaccaca\r\n" +
				"aatgttagccagcatcgttgagcaacctataggggcattacggtgtagctcatttttcag\r\n" +
				"ttcactgataggcatctggaattgaggggttcaatcagcatttagtataagcttcgggga\r\n" +
				"acggggcccatttcatcaggcctttgacgccgtccaaggacccccgttcctgccatctta\r\n" +
				"tacctcgggatatgtcggggtgtgtgtgtgtgtagcgccaatcgtaacccattgcgatcg\r\n" +
				"gttgcgaacgaggctcagtggtaaaacgcatatagtagaggtgagccctcgagttgcctt\r\n" +
				"caatatgttttgggcccggccatggttactatactgcgtattgtttccggatccaccagg\r\n" +
				"gggcgagcaatcccctcgtcagtgctgctgatgagtaaggacatgctttcattttgccta\r\n" +
				"ggaaagtctactggatttcgacgactctgatctcattaggggtcagttcttggtttatac\r\n" +
				"ggtatgcccgttagataagtgactctggggggaggtgatattccccacttcatattaatt\r\n" +
				"gcgatgttttttcaaaggtacggagatctaccgagtctatgttcattattcggttcactg\r\n" +
				"caggaggaggtcatgtgactcggaaggtaacaccgagttttcacaaggacaaacgtatcg\r\n" +
				"ggtgggttcgattaactttgagaggccatagactctccaatccttcacctagatgtcgca\r\n" +
				"gtgtgctccaagcacgaggaacatgcgtgccttgcttagcaaagataatgtctcggtcgg\r\n" +
				"tcgagattcccaatatagacctgtggcctgcggcgaaaactgcgattcagtgggaagaaa\r\n" +
				"aacaaacgtcgcgtacgctagggtcgagttcgccctcgtcgaatgcacagacggcagaat\r\n" +
				"taagggacaaggcttctactaccgggcatagcacatatttcgcccgagagcgtcgtcccg\r\n" +
				"gccacccataatgatccgcgaacctacctttcgataaacctaaggaatttctcgttggtg\r\n" +
				"aagggccggacatgaagtctcttgacacatgtgagtacggctattgaacgctgcgccgtc\r\n" +
				"aaacgcgggagccatcctgctttgcgcgttacacattattgctgagcccgttgcgggaat\r\n" +
				"cgccgacagcgccgccattcgtccaaacggtgctctccggtggagttttaggcaatcgca\r\n" +
				"actgtacactagtaactatacatcaggtagcacggctgggctgtataccgaggcaggtcg\r\n" +
				"aacgtaacgttcagagcaactatccaagggggtggcaccctgaaatgcacgccctcccaa\r\n" +
				"gggggggcgcctattgttacgatagctaacaggacacttagcgtatgatagtcgcgggtt\r\n" +
				"gtactttggtccaaatgcaaaaaatgtcgcacttttgagtagcgcgcagctgcaaccatc\r\n" +
				"ttcatgcatcttatatctacgtggtgtcgccttcctcagttctgctgaatgcgaggtgca\r\n" +
				"atgtccgagacacctgtcttgaggtttcaccgacagtgttccttcccgtataacgcgtgt\r\n" +
				"taatatccgtagatccactatagcgtaatgtgaaatagatcggcaaatactgactatacc\r\n" +
				"tttgatggatatcctcaaatcacagaagcagaagtaactccatacgccggatactcaccg\r\n" +
				"gtatcaatattcgtctaatagagcatgctgtattcatctgctcgacggttgaagagcatc\r\n" +
				"tacactactgtcacataaactctaacgggttttttacaatacgttctgggtaacaaacac\r\n" +
				"atctgggccggcaggaaggcttctgtcatgttttctagaatacctaaatatatccatctt\r\n" +
				"ttgtcaagcctgtatcaacatagacctatatagcatccgcgtctttcctcggtcacaggc\r\n" +
				"ttatacctttcaacattcttagaggacattaattagcgcgatgactactttcgcacactt\r\n" +
				"acgcatggggtcttctcgcgattgtagatggctagacgacgcgtaccttgcgatccgctt\r\n" +
				"gtaacggctgcagcggttgaggatcggttcggagttactgttcgccccttgtgaacggtt\r\n" +
				"aacttcttccggcgcgttgctttgttgaccaatgtaaggccaggaagaccacgactcgct\r\n" +
				"tgctttaagttgtacattcatagactcccaacagtggccgccgctacgatgagaggtccg\r\n" +
				"atcctggcttctctcgacggacctttcccatcggaaggaggtcctgggatgtgatagagt\r\n" +
				"catgaactcgtaattatccatgctctgttggtgcaacgcacttcacgttaacagttggat\r\n" +
				"gatgatagactctatttgttaagaacttatgaaacccccgtcatcatggtggtacactga\r\n" +
				"tcgtgaaaccacgtaccacgagtcattattatcggtctctgtgatcacattggcccagag\r\n" +
				"catgcggttagccatgaacattctaattgcattctgttcttgatggcacccgggatgctc\r\n" +
				"agagacgaggctcttggattgttacgatgaatagagtagagttcactccttaatatatac\r\n" +
				"gtgcggactgacaccacatacaaggaagtctggttatggccacaggcccttctttggtac\r\n" +
				"tttaattgggcggatgccgagtgttgggcggtcttatggtttcgcccgtataccagacgg\r\n" +
				"cctcgtcaagcgcgtgtgctggagctcgcttctctctgcggtgtgcacttagtcacaaac\r\n" +
				"gattttcgaactcgagtgctatgactaacacgctacccgcgggataggaaatactttcca\r\n" +
				"atcccaccctgcgtcagctacgtataacacggcggctgtgacggcgatagtataagtgag\r\n" +
				"agatacttacctaaccgctttacacacacttcaaccctgtatattgccctccatatatgg\r\n" +
				"ctgtgcgagacgaatgtcatcaacaccatttggtcatgataaggcaagtgaatgaagagt\r\n" +
				"cactcccacctaccatctgggtaagcaaaacgtcgaccagtcctgtttgtgagctagggg\r\n" +
				"gtctggtggggtttaattaaggcgctgacagcggggtgtaccggcgctcatgaggacgtc\r\n" +
				"atcgaaccagagcggtcaagggtgacaaactccgtaacaatcactgaatttgcggggtca\r\n" +
				"cactggtattatgacaacactctattgcgtatatttcatcagaaaatcattcaggcgcgc\r\n" +
				"cggagggatcagggtacataaccgcaacagtgccccgacaacaacttggcttagcttttt\r\n" +
				"agccagtgttgctgatcactccggcctcgtgacaagtctatcccagccgcatcaggtttg\r\n" +
				"ccctacagacataaccgatgggtattgaactggctcatcgaaattagagaacccccccaa\r\n" +
				"gggcgccttacgcgccgaatataagagtcgtagtatgccaggattcacccgactcgaact\r\n" +
				"atcgatcatggggcgcgcacaatggcaaaaactgcaacccgggaggcgtcggttttatcc\r\n" +
				"ggctaatagagtaaacttttcaatgctacagtgtctaaacccaaagtacaacttcagcca\r\n" +
				"tattcgtccctagcccagcccatgagcccaattagtcctgaaccaaatacgcgaccgggc\r\n" +
				"aacccaagttgggtcgagctgctcaatgctactggcgacgctccgcctgtcgccagcaag\r\n" +
				"ctgtgtcatgtgcttggggaagagtgagtgatcctttcaattacgtttgtaggatatcag\r\n" +
				"ttaaatgtttgtcgacacgtaaccccggatcggtcttccaagatgatttttaagcgttgg\r\n" +
				"tggctctcaacaaccgaattccggcaccctgcagcgagacttacacccttccatggggat\r\n" +
				"cgggccaaaaacgaaattagaaaaactcaactgggcgcagaaaacgttggcggtaaaagg\r\n" +
				"ggaatagcataatccctaaaaggtcgacaccgaggatagcttccactagtgattcggcga\r\n" +
				"ccatactttgctcattcctagcccgttgtaacctactggtttaatgttattttacaaagc\r\n" +
				"catgatcatggtatgggcctgccggtttatggccttatgcttctatatcaaaatgttagg\r\n" +
				"cacgacaagagcttaccacccgcggagctcactgagctttttcttctggctggtcattgc\r\n" +
				"ccaagtgaagtgcatgtgacgcttgcctgtgttaataatctagggagctaaacatggata\r\n" +
				"gaagtacctttgttggggcagaaaaagaatagagctgcagaaggggtattctcgatacaa\r\n" +
				"gagggtacgttatatagtcaggagaccacaaggagagtcgggacagaagcaaacccggcc\r\n" +
				"gaaaggcccaattcaccacggccagcctgaagtcggttcaaacctctcccatcaatcgct\r\n" +
				"tgtatttagccctaggcatgctgagccgcaatccgccaactaccagtcaggtgtacagtg\r\n" +
				"cctccaatccacggctcatacctaatgctcacacagggatggtacgcctaacaaggtacc\r\n" +
				"ttctcgcggccccttatgcttggattatggctcgttgttgacgttaggttgccttctctc\r\n" +
				"gccaaaacaaggtccgacggccttctgcggcgctgatctgtagtgcctggataactaggt\r\n" +
				"cgggactatcccactacgtcgcttacgacaatcccaccacttgggtcaaagtaataggat\r\n" +
				"aagctacaagttcgttcgtcgtcgacagagtccttgtaggaaatgagctagcagggaaaa\r\n" +
				"cggggacttaaactacatctttgggacgcgactgttagaaatatgtcgtcagtgaacgtc\r\n" +
				"gttgtgtttcttgtcataatgcacgaagcagcgactcaatccccagatctggcgggcccc\r\n" +
				"aaaaattaggatacaatgtcgtcaaggatacactctatgcgcactaagttaactataccc\r\n" +
				"cctttcgtctaacatcccgatattatttgagctaaacagatcgattacgcggactagcac\r\n" +
				"gatccttcatggactaaattttcaaaacaatgccgcgatggccctcttgcttcgactgct\r\n" +
				"tagcttaacgaatgttgtcctgtagcgggccctggagcctttatcgggggtgtacctaac\r\n" +
				"cctattacccggaagccagcggccttggcagtccaagacactcgccagaccgccgccagt\r\n" +
				"catcctactaatatggtattgatgcacccgtccaccttggttgtacacaacctggctata\r\n" +
				"ctggcggaagtgcacggaaaaatgatgcgcacttggcctttgttacatgtctcgacggga\r\n" +
				"tgggccgataagtgacatcttgtcgaatcaccaccaggtgtaggtgtgactcaatgatac\r\n" +
				"aaaattaggtccagagacacggacatcgtccgccaaaacctacacgttagttaatgctcg\r\n" +
				"agtgcccataaaagtaaactgtaagcgtcggcgcgaccgagacccctcatcattggtcaa";

		EditDistance editDistance = new EditDistance(DNA1, DNA2);

		long startTime = System.currentTimeMillis();
		editDistance.calculate();
		long endTime = System.currentTimeMillis();
		long duration = (endTime - startTime);

		System.out.println("Il tempo impiegato per la prima è: " + duration);

		EditDistanceParallel editDistanceParallel = new EditDistanceParallel(DNA1, DNA2, 3);

		startTime = System.currentTimeMillis();
		editDistanceParallel.calculate();
		endTime = System.currentTimeMillis();
		duration = (endTime - startTime);

		System.out.println("Il tempo impiegato per la seconda è: " + duration);

	}

}
